#!/usr/bin/env bash

wickExplorer OS wick-base os
wickGetArgument TZ 0 "$@"

case "$OS" in
    debian|ubuntu)
        TZ=${TZ:-Etc/UTC}
        ;;

    *)
        TZ=${TZ:-UTC}
esac

wickInfo "Updating timezone: $TZ"
TIMEZONE=/etc/timezone
TZDATA_DIR=/usr/share/zoneinfo
LOCALTIME=/etc/localtime
USE_SYMLINK=false

case "$OS" in
    amazon)
        timezone-update-localtime "$LOCALTIME" "$TZDATA_DIR/$TZ" "$USE_SYMLINK"
        timezone-update-sysconfig-clock "$TZ"
        ;;

    fedora|redhat|centos)
        timezone-update-sysconfig-clock "$TZ"
        ;;

    debian|ubuntu)
        timezone-update-timezone "$TZ" "$TIMEZONE"
        ;;

    pld)
        timezone-update-sysconfig-timezone "$TZ" "$TZDATA_DIR"
        ;;

    *)
        wickWarn "Unknown OS: $OS"
        wickWarn "Updating the timezone with a generic method"
        timezone-update-localtime "$LOCALTIME" "$TZDATA_DIR/$TZ" "$USE_SYMLINK"
esac
