#!/usr/bin/env bash
# Sets the time zone to a specified zone, defaulting to UTC.
#
# $1 - Optional time zone identifier.  Defaults to `Etc/UTC` for
#      Debian/Ubuntu and `UTC` for all others.
#
# The actions of this formula are based heavily on
# [timezone-ii](https://github.com/L2G/timezone-ii), a Chef recipe.
#
# Examples
#
#     # Set to UTC
#     wickFormula timezone
#
#     # Set to CST6CDT
#     wickFormula CST6CDT
#
# Returns nothing.
declare os timezoneValue

wickExplorer os wick-base os
wickGetArgument timezoneValue 0 "$@"

case "$os" in
    debian|ubuntu)
        timezoneValue=${timezoneValue:-Etc/UTC}
        ;;

    *)
        timezoneValue=${timezoneValue:-UTC}
esac

wickInfo "Updating timezone: $timezoneValue"
timezoneFile=/etc/timezone
tzDataDir=/usr/share/zoneinfo
localtimeFile=/etc/localtime

case "$os" in
    amazon)
        timezoneUpdateLocaltime "$localtimeFile" "$tzDataDir/$timezoneValue"
        timezoneUpdateSysconfigClock "$timezoneValue"
        ;;

    fedora|redhat|centos)
        timezoneUpdateSysconfigClock "$timezoneValue"
        ;;

    debian|ubuntu)
        timezoneUpdateTimezone "$timezoneValue" "$timezoneFile"
        ;;

    pld)
        timezoneUpdateSysconfigTimezone "$timezoneValue" "$tzDataDir"
        ;;

    *)
        wickWarn "Unknown OS: $os"
        wickWarn "Updating the timezone with a generic method"
        timezoneUpdateLocaltime "$localtimeFile" "$tzDataDir/$timezoneValue"
esac
