#!/usr/bin/env bash
# Installs OpenJDK 1.7 JRE.
#
# Examples
#
#   wickFormula openjdk-1.7
#
# Returns nothing
wickExplorer os wick-base os

case "$os" in
    debian|ubuntu)
        wickPackage openjdk-7-jre
        ;;

    *)
        wickPackage java-1.7.0-openjdk
        ;;
esac
