#!/usr/bin/env bash
# Installs [mo](https://github.com/tests-always-included/mo) mustache template
# parser into `/usr/local/bin/` and adds the ability to use "mo" templates with
# `wickMakeFile` (in the wick-base formula).
#
# Examples
#
#   wickFormula mo
#
# See [templates] for more about the template system.
#
# [templates]: ../../doc/templates.md
#
# Returns nothing.
wickMakeFile mo /usr/local/bin/
