#!/usr/bin/env bash
# Installs `ntp` Network Time Protocol package and `ntpdate` set time utility.
#
# Examples
#
#   wickFormula ntp
#
# Returns nothing
declare os serviceName

wickExplorer os wick-base os
serviceName=ntpd

if [[ "$os" == ubuntu ]]; then
    serviceName=ntp
fi

wickInfo "Installing ntp and ntpdate packages"
wickPackage ntp ntpdate

wickInfo "Enabling $serviceName"
wickService enable "$serviceName"
