#!/usr/bin/env bash
# Adds the EPEL repository to yum.  Does not do anything for other package
# managers.
#
# Examples
#
#   wickFormula yum-epel
#
# Returns nothing.
wickExplorer os wick-base os

case "$os" in
    redhat|centos)
        wickInfo "Adding EPEL repository"
        ;;

    *)
        wickInfo "EPEL repository not needed for this OS: $os"
        exit
esac

installed=$(rpm -qa | grep ^epel-release- || true)

if [[ ! -z "$installed" ]]; then
    wickInfo "EPEL package already installed: $installed"
    exit
fi

package=$(rpm -q --whatprovides /etc/redhat-release)

wickTempDir temp

(
    cd "$temp"

    case "$package" in
        *.el5.*)
            wickGetUrl "http://dl.fedoraproject.org/pub/epel/5/x86_64/epel-release-5-4.noarch.rpm" epel.rpm
            ;;

        *.el6.*)
            wickGetUrl "http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm" epel.rpm
            ;;

        *.el7.*)
            wickGetUrl "http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm" epel.rpm
            ;;
    esac

    if [[ -f epel.rpm ]]; then
        rpm -Uvh epel.rpm
    fi
)
