#!/usr/bin/env bash
# Adds the EPEL repository to yum.  Does not do anything for other package
# managers.
#
# Examples
#
#   wickFormula yum-epel
#
# Returns nothing.
declare os temp

wickExplorer os wick-base os

case "$os" in
    redhat|centos)
        wickInfo "Adding EPEL repository"
        ;;

    *)
        wickInfo "EPEL repository not needed for this OS: $os"

        exit
esac

installed=$(rpm -qa | grep ^epel-release- || true)

if [[ -n "$installed" ]]; then
    wickInfo "EPEL package already installed: $installed"

    exit
fi

package=$(rpm -q --whatprovides /etc/redhat-release)

wickTempDir temp

(
    cd "$temp"

    case "$package" in
        *.el5.*)
            wickGetUrl "http://dl.fedoraproject.org/pub/epel/epel-release-latest-5.noarch.rpm" epel.rpm
            ;;

        *.el6.*)
            wickGetUrl "http://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm" epel.rpm
            ;;

        *.el7.*)
            wickGetUrl "http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm" epel.rpm
            ;;
    esac

    if [[ -f epel.rpm ]]; then
        rpm -Uvh epel.rpm
    fi
)
