#!/usr/bin/env bash
# This installs a name server caching daemon.  The `unscd` package is preferred
# over `nscd`, but the two are essentially interchangeable.
#
# --start - Starts the service.  If not specified, the service will not be
#           running when the formula finishes.
#
# Examples
#
#   wickFormula nscd
#
#   wickFormula nscd --start
#
# Returns nothing.
wickGetOption start start "$@"

if wickPackage --exists unscd; then
    wickPackage unscd
    wickService enable unscd
    wickService force-state unscd "$start"
else
    wickPackage nscd
    wickService enable nscd
    wickService force-state unscd "$start"
fi
