#!/usr/bin/env bash

wickInfo "Installing RVM"

wickDebug "Adding GPG key"
gpg --keyserver hkp://keys.gnupg.net --recv-keys D39DC0E3

wickDebug "Installing RVM"
wickGetUrl https://get.rvm.io | bash -s stable "$@"
