#!/usr/bin/env bash
# This installs RVM from [http://get.rvm.io/](http://get.rvm.io/).  Passes all
# extra parameters to the installer.
#
# $@ - All options are passed directly to the installer.
#
# For examples of options see
# [https://rvm.io/rvm/install](https://rvm.io/rvm/install).
#
# Examples
#
#   # Install RVM and the latest Ruby
#   wickFormula rvm stable --ruby=latest
#
# Returns nothing.
wickInfo "Installing RVM"

wickDebug "Adding GPG key"
gpg --keyserver hkp://keys.gnupg.net --recv-keys D39DC0E3

wickDebug "Installing RVM"
wickGetUrl https://get.rvm.io | bash -s stable "$@"
