#!/usr/bin/env bash
# Installs `dig` to query domain name system name servers.
#
# Examples
#
#   wickFormula dig
#
# Returns nothing.
declare os

wickExplorer os wick-base os

case "$os" in
    centos|redhat)
        wickPackage bind-utils
        ;;

    ubuntu)
        wickPackage dnsutils
        ;;

    *)
        wickPackage dig
        ;;
esac
