#!/bin/bash

timezone-update-localtime() {
    wick-debug "Updating tzdata: $2 -> $1"

    if [[ ! -f "$2" ]]; then
        wick-error "Can not find timezone file: $2"
        return 1
    fi

    rm "$1"

    if $3; then
        # Use symlink
        wick-debug "Setting timezone with symlink"
        ln -s "$2" "$1"
    else
        # Copy
        wick-debug "Setting timezone by copying"
        cp "$2" "$1"
    fi

    chown root:root "$1"
    chmod 0644 "$1"
}
