#!/usr/bin/env bash
# Update the timezone file.
#
# $1 - The new timezone.
# $2 - The file to use.
#
# Examples
#
#   timezoneUpdateTimezone UTC /etc/timezone
#
# Returns nothing.
timezoneUpdateTimezone() {
    local amended

    wickDebug "Updating timezone using tzdata: $2"
    rm "$2"
    echo "$1" > "$2"
    chown root:root "$2"
    chmod 0644 "$2"
    dpkg-reconfigure -f noninteractive tzdata
    amended=$(cat "$2")

    if [[ "$1" != "$amended" ]]; then
        wickWarn "dpkg-reconfigure changed the timezone: $amended"
    fi
}
