#!/usr/bin/env bash
# Updates the timezone in /etc/sysconfig/timezone.
#
# $1 - The new time zone.
# $2 - The zoneinfo directory.
#
# Examples
#
#   timezoneUpdateSysconfigTimezone UTC /usr/share/zoneinfo
#
# Returns nothing.
timezoneUpdateSysconfigTimezone() {
    local tzFile

    wickInfo "Updating /etc/sysconfig/timezone"
    tzFile=/etc/sysconfig/timezone
    rm "$tzFile"

    {
        echo "TIMEZONE=\"$1\""
        echo "ZONE_INFO_DIR=\"$2\""
        echo "ZONE_INFO_SCHEME=\"posix\""
    } > "$tzFile"

    chown root:root "$tzFile"
    chmod 0644 "$tzFile"

    wickService reload timezone
}
