#!/usr/bin/env bash

timezone-update-sysconfig-clock() {
    if wickCommandExists timedatectl; then
        wickDebug "Using timedatectl to set timezone"
        timedatectl --no-ask-password set-timezone "$1"
    else
        wickDebug "Updating /etc/sysconfig/clock"
        rm /etc/sysconfig/clock
        echo "ZONE=$TZ" > /etc/sysconfig/clock
        chown root:root /etc/sysconfig/clock
        chmod 0644 /etc/sysconfig/clock

        if [[ -x /usr/sbin/tzdata-update ]]; then
            /usr/sbin/tzdata-update
        fi
    fi
}
