#!/usr/bin/env bash
# Updates the timezone in /etc/sysconfig/timezone.
#
# $1 - The new time zone.
# $2 - The zoneinfo directory.
#
# Examples
#
#   timezoneUpdateSysconfigTimezone UTC /usr/share/zoneinfo
#
# Returns nothing.
timezoneUpdateSysconfigTimezone() {
    local TZFILE

    wickInfo "Updating /etc/sysconfig/timezone"
    TZFILE=/etc/sysconfig/timezone
    rm "$TZFILE"
    echo "TIMEZONE=\"$1\"" >> "$TZFILE"
    echo "ZONE_INFO_DIR=\"$2\"" >> "$TZFILE"
    echo "ZONE_INFO_SCHEME=\"posix\"" >> "$TZFILE"
    chown root:root "$TZFILE"
    chmod 0644 "$TZFILE"

    wickService reload timezone
}
