#!/usr/bin/env bash
# Updates the localtime file.
#
# $1 - Time zone
# $2 - File to update
# $3 - Use a symlink when this is a non-empty string
#
# Example:
#
#   timezoneUpdateLocaltime UTC /etc/localtime
#
# Returns 0 on success.
timezoneUpdateLocaltime() {
    wickDebug "Updating tzdata: $2 -> $1"

    if [[ ! -f "$2" ]]; then
        wickError "Can not find timezone file: $2"
        return 1
    fi

    rm "$1"

    if [[ -n "${3-}" ]]; then
        # Use symlink
        wickDebug "Setting timezone with symlink"
        ln -s "$2" "$1"
    else
        # Copy
        wickDebug "Setting timezone by copying"
        cp "$2" "$1"
    fi

    chown root:root "$1"
    chmod 0644 "$1"
}
