#!/usr/bin/env bash
# Updates the timezone in sysconfig/clock.
#
# $1 - The new timezone.
#
# Examples
#
#   timezoneUpdateSysconfigClock UTC
#
# Returns nothing.
timezoneUpdateSysconfigClock() {
    if wickCommandExists timedatectl; then
        wickDebug "Using timedatectl to set timezone"
        timedatectl --no-ask-password set-timezone "$1"
    else
        wickDebug "Updating /etc/sysconfig/clock"
        rm -f /etc/sysconfig/clock
        echo "ZONE=$1" > /etc/sysconfig/clock
        chown root:root /etc/sysconfig/clock
        chmod 0644 /etc/sysconfig/clock

        if [[ -x /usr/sbin/tzdata-update ]]; then
            /usr/sbin/tzdata-update
        fi
    fi
}
