#!/usr/bin/env bash

timezone-update-timezone() {
    local AMENDED

    wickDebug "Updating timezone using tzdata: $2"
    rm "$2"
    echo "$1" > "$2"
    chown root:root "$2"
    chmod 0644 "$2"
    dpkg-reconfigure -f noninteractive tzdata
    AMENDED=$(cat "$2")

    if [[ "$1" != "$AMENDED" ]]; then
        wickWarn "dpkg-reconfigure changed the timezone: $AMENDED"
    fi
}
