#!/usr/bin/env bash
# Installs OpenJDK 1.7 JDK.
#
# Examples
#
#   wickFormula openjdk-1.7-jdk
#
# Returns nothing.
declare os

wickExplorer os wick-base os

case "$os" in
    debian|ubuntu)
        wickPackage openjdk-7-jdk
        ;;

    *)
        wickPackage java-1.7.0-openjdk-devel
        ;;
esac
