#!/usr/bin/env bash
# Restart the nscd or unscd daemon.  This is used whenever you make changes to
# nsswitch or other times when a cached user hit/miss would cause issues.
#
# Examples
#
#   nscdRestart
#
# Returns nothing.
nscdRestart() {
    local result

    wickStrictRun result wickPackage --exists unscd

    if [[ "$result" -eq 0 ]]; then
        wickService restart unscd
    else
        wickService restart nscd
    fi
}
