#!/bin/bash

cron-add() {
    local FILENAME JOBNAME OPTIONS

    wick-get-argument JOBNAME 0 "$@"
    wick-get-argument FILENAME 1 "$@"
    wick-get-options OPTIONS "$@"

    if [[ -d /etc/cron.d/ ]]; then
        wick-make-file "$FILENAME" "/etc/cron.d/$JOBNAME" "${OPTIONS[@]-}"
    else
        echo "# BEGIN: $JOBNAME" >> /etc/crontab
        wick-make-file "$FILENAME" - "${OPTIONS[@]-}" >> /etc/crontab
        echo "# END: $JOBNAME" >> /etc/crontab
    fi
}
