#!/usr/bin/env bash

cron-add() {
    local FILENAME JOBNAME OPTIONS

    wickGetArgument JOBNAME 0 "$@"
    wickGetArgument FILENAME 1 "$@"
    wickGetOptions OPTIONS "$@"

    if [[ -d /etc/cron.d/ ]]; then
        wickMakeFile "$FILENAME" "/etc/cron.d/$JOBNAME" "${OPTIONS[@]-}"
    else
        echo "# BEGIN: $JOBNAME" >> /etc/crontab
        wickMakeFile "$FILENAME" - "${OPTIONS[@]-}" >> /etc/crontab
        echo "# END: $JOBNAME" >> /etc/crontab
    fi
}
