#!/usr/bin/env bash

cron-remove() {
    if [[ -d /etc/cron.d/ ]]; then
        if [[ -f "/etc/cron.d/$1" ]]; then
            wickDebug "Removing cron job: $1"
            rm "/etc/cron.d/$1"
        else
            wickDebug "Cron job does not exist: $1"
        fi
    else
        wickDebug "Purging job from crontab: $1"
        sed -i --follow-symlinks "/^# BEGIN: $1$/,/^# END: $1$/d" /etc/crontab
    fi
}
