#!/usr/bin/env bash
# Removes a job from cron.  Works only for jobs that were added with `cronAdd`.
#
# $1 - The name of the cron job to remove.
#
# Examples
#
#   # Add and remove a cron job
#   cronAdd update-mongo-v2 --template update-mongo.mo
#   cronRemove update-mongo-v1
#
# Returns nothing.
cronRemove() {
    if [[ -d /etc/cron.d/ ]]; then
        if [[ -f "/etc/cron.d/$1" ]]; then
            wickDebug "Removing cron job: $1"
            rm "/etc/cron.d/$1"
        else
            wickDebug "Cron job does not exist: $1"
        fi
    else
        wickDebug "Purging job from crontab: $1"
        sed -i --follow-symlinks "/^# BEGIN: $1$/,/^# END: $1$/d" /etc/crontab
    fi
}
