#!/usr/bin/env bash

github-get-archive() {
    repo=$1
    tag=${2:-master}
    dest=${3:-"${repo##*/}.tar.gz"}
    username=${4:-""}
    password=${5:-""}
    userOption=()

    if [[ -n $username ]]; then
        userOption=("--user '$username:$password'")
    fi

    curl -s -L ${userOption[@]} "https://github.com/$repo/tarball/$tag" > "$dest"
}
