#!/usr/bin/env bash
# This installs the Kermit (from the `ckermit` package), allowing file transfer
# to and from a remote machine.
#
# Examples
#
#   wickFormula kermit
#
# Returns nothing.
wickPackage ckermit
