#!/usr/bin/env bash

wickExplorer OS wick-base os

case "$OS" in
    debian|ubuntu)
        wickPackage tomcat7
        ;;

    *)
        wickPackage tomcat
        ;;
esac

wickService enable tomcat
wickService restart tomcat
