#!/usr/bin/env bash
# Installs Tomcat 7, which depends on Java 1.7 or Java 1.8.
#
# --java-1.8 - Depend on Java 1.8 instead of 1.7.
#
# Examples
#
#   # Use Java 1.7
#   wickFormula tomcat-7
#
#   # Use Java 1.8
#   wickFormula tomcat-8
#
# Returns nothing.
wickExplorer os wick-base os

case "$os" in
    debian|ubuntu)
        wickPackage tomcat7
        ;;

    *)
        wickPackage tomcat
        ;;
esac

wickService enable tomcat
wickService restart tomcat
