#!/usr/bin/env bash
# Adds a configuration entry into dnsmasq.
#
# $1   - Name of the rule to generate.
# $2-@ - The configuration line.
#
# The name can be later used by dnsmasqRemove to remove this line.
#
# Examples
#
#   dnsmasqAddConfig consul "server=/consul./127.0.0.1#8600"
#
# Returns nothing.
dnsmasqAddConfig() {
    local NAME

    NAME=$1
    shift
    echo "$@" > "/etc/dnsmasq.d/$NAME"

    if pidof dnsmasq > /dev/null; then
        wickService restart dnsmasq
    fi
}
