#!/usr/bin/env bash

dnsmasq-add-config() {
    local NAME

    NAME=$1
    shift
    echo "$@" > "/etc/dnsmasq.d/$NAME"

    if pidof dnsmasq > /dev/null; then
        wickService restart dnsmasq
    fi
}
