#!/bin/bash

set -e
. /usr/local/lib/wick-infect

replace-in-file() {
    local FN SEARCH WANTED

    FN="$1"
    WANTED="$2"
    SEARCH="$3"

    if ! grep -q "^$WANTED" "$FN"; then
        if grep -q "^$SEARCH" "$FN"; then
            wick-debug "Updating $FN: $WANTED"
            sed -i --follow-symlinks 's/^'"$SEARCH"'.*/'"$WANTED"'/' "$FN"
        else
            wick-debug "Adding to $FN: $WANTED"
            echo "$WANTED" >> "$FN"
        fi
        return 0
    else
        wick-debug "$FN is already changed"
        return 1
    fi
}

show-help() {
    cat <<EOF
Set the hostname of the machine, with support for templates

Usage:
    set_hostname [OPTIONS] hostname.domain.name

If no domain name is given, "localdomain" is used instead.
You can use the following patterns:

    {{IP}}      Replaced with the IP, such as 127-0-0-1.
                Example:  apache-{{IP}}.internal
                Result:   apache-192-168-0-3.internal

Options:
    --iface=IF  Detect the IP of this specific interface
    --help      This help message
    --reload    Reload if necessary
    --verbose   Be verbose about what's going on
EOF
}

wick-get-option HELP help "$@"
wick-get-option RELOAD_FLAG reload "$@"
wick-get-option VERBOSE verbose "$@"
wick-get-option IFACE iface "$@"
wick-get-argument FULL 0 "$@"

if [[ ! -z "$VERBOSE" ]]; then
    DEBUG=true
fi

if [[ ! -z "$HELP" ]] || [[ -z "$FULL" ]]; then
    show-help
    exit 1
fi

HOST=$(echo "$FULL" | cut -d '.' -f 1)
DOMAIN=$(echo "$FULL" | cut -d '.' -f 2- -s)
DOMAIN=${DOMAIN:-localdomain}
IFCONFIG_ARGS=("-v")

if [[ ! -z "$IFACE" ]]; then
    IFCONFIG_ARGS=("${IFCONFIG_ARGS[@]}" "$IFACE")
fi

IP=$(ifconfig "${IFCONFIG_ARGS[@]}" | grep inet\ addr | head -n 1)
IP=${IP#*:}
IP=${IP%% *}
IP=${IP//./-}
HOST=${HOST//\{\{IP\}\}/$IP}
FULL="${HOST}.${DOMAIN}"

wick-debug "Setting hostname to $FULL"

#
# Update hostname
#
RELOAD=false

if replace-in-file /etc/sysconfig/network HOSTNAME=$FULL HOSTNAME=; then
    RELOAD=true
fi

if replace-in-file /etc/sysctl.conf kernel.hostname=$HOST kernel.hostname=; then
    RELOAD=true
fi

if replace-in-file /etc/hosts "127.0.0.1 $FULL $HOST localhost" "127.0.0.1"; then
    RELOAD=true
fi

if [[ "$(hostname)" != "$HOST" ]]; then
    wick-debug "Setting hostname"
    hostname "$HOST"
    RELOAD=true
else
    wick-debug "Hostname is already changed"
fi

if [[ "$(domainname)" != "$DOMAIN" ]]; then
    wick-debug "Setting domainname"
    domainname "$DOMAIN"
    RELOAD=true
else
    wick-debug "Domainname is already changed"
fi

if [[ ! -z "$RELOAD_FLAG" ]] && $RELOAD; then
    wick-debug "Restarting network to get hostname updated everywhere"
    service network restart
elif $RELOAD; then
    wick-debug "Not reloading even though changes were made"
else
    wick-debug "Skipping network reload because no changes were made"
fi
