#!/usr/bin/env bash
# This installs the `lrzsz` package, providing the `rz` and `sz` commands to
# send/receive files using ZModem.
#
# Examples
#
#   wickFormula zmodem
#
# Returns nothing.
wickPackage lrzsz
