#!/usr/bin/env bash
# Installs OpenJDK 1.8 JDK.
#
# Examples
#
#   wickFormula openjdk-1.8-jdk
#
# Returns nothing.
wickExplorer OS wick-base os

case "$OS" in
    debian|ubuntu)
        wickPackage openjdk-8-jdk
        ;;

    *)
        wickPackage java-1.8.0-openjdk-devel
        ;;
esac
