#!/usr/bin/env bash
# Returns success (0) when SELinux is installed and enabled.
#
# Examples
#
#   # Convoluted, but necessary because of strict mode and newer Bash.
#   # See doc/contexts-that-disable-exit-on-error.md
#   local result
#
#   wickStrictRun result selinuxIsEnabled
#
#   if [[ "$result" -eq 0 ]]; then
#       wickWarn "This does not work well with SELinux enabled"
#   fi
#
# Returns true if it is enabled and it is being enforced.
selinuxIsEnabled() {
    local enforced getenforceExists semanageExists

    wickStrictRun getenforceExists wickCommandExists getenforce
    wickStrictRun semanageExists wickCommandExists semanage

    if [[ "$getenforceExists" -ne 0 && "$semanageExists" -ne 0 ]]; then
        wickDebug "SELinux appears to be not installed"

        return 1
    fi

    enforced=$(getenforce)

    if [[ "$enforced" == "Disabled" ]] || [[ "$enforced" == "Permissive" ]]; then
        wickDebug "SELinux is not enforced"

        return 1
    fi

    return 0
}
