#!/usr/bin/env bash
# Returns success (0) when SELinux is installed and enabled.
#
# Examples
#
#   if selinuxIsEnabled; then
#       wickWarn "This does not work well with SELinux enabled"
#   fi
#
# Returns true if it is enabled and it is being enforced.
selinuxIsEnabled() {
    local enforced

    if ! wickCommandExists getenforce && ! wickCommandExists semanage; then
        wickDebug "SELinux appears to be not installed"

        return 1
    fi

    enforced=$(getenforce)

    if [[ "$enforced" == "Disabled" ]] || [[ "$enforced" == "Permissive" ]]; then
        wickDebug "SELinux is not enforced"

        return 1
    fi

    return 0
}
