#!/usr/bin/env bash
# Internal: Changes a single setting for sshd based on the value from
# an option passed to the formula.
#
# $1   - Config file to update
# $2   - Setting to change
# $3   - Name of the option
# $4-@ - All options passed to the formula.
#
# Scans through `$options` for `--$3` or `--$3=no`.  If the value is "no",
# disables the option (adds "$1 no" to the config file).  When the value
# is "true" (because that's how wickGetOption works) it enables the setting
# in the config file.
#
# Returns nothing.
sshdTweakSetting() {
    local config name setting val

    config=$1
    setting=$2
    name=$3
    shift 3
    wickGetOption val "$name" "$@"

    case "$val" in
        true)
            wickInfo "Enabling $setting"
            wickSetConfigLine "$config" "$setting yes"
            ;;

        no)
            wickInfo "Disabling $setting"
            wickSetConfigLine "$config" "$setting no"
            ;;
    esac
}
