#!/usr/bin/env bash
# This happens here instead of the run script because the depends file should
# execute on the "control master" instead of the "target machine".  At the
# time of this writing, Wick does not allow for remotely provisioning
# machines, but it is a direction that is desired for the project.
#
# Starting in deepest parent, write lib/* with a header
showAllLibFunctions() {
    local file

    if [[ -d "$1/parent" ]]; then
        showAllLibFunctions "$1/parent" || return $?
    fi

    if [[ -d "$1/lib" ]]; then
        for file in "$1/lib/"*; do
            if wickIsValidScript "$file"; then
                echo "# $file"
                cat "$file" || return $?
                echo ""
            fi
        done
    fi
}

(
    echo "#!/usr/bin/env bash"
    echo "#"
    echo "# This file was created by the wick-infect formula"
    echo ""

    # This line must work with sh in case it is sourced by the wrong
    # shell interpreter.
    echo "[ -n \"\$BASH_VERSION\" ] || return 1"

    # Having $POSIXLY_CORRECT enabled can cause problems because Bash
    # limits itself to only POSIX commands.  We want full Bash.
    echo "[[ \"\$POSIXLY_CORRECT\" != \"y\" ]] || return 1"
    echo ""
    showAllLibFunctions . || exit $?
) > "$WICK_FORMULA_DIR/files/wick-infect"

wickFormula wick-base
