#!/usr/bin/env bash
# This happens here instead of the run script because the depends file should
# execute on the "control master" instead of the "target machine".  At the
# time of this writing, Wick does not allow for remotely provisioning
# machines, but it is a direction that is desired for the project.
#
# Starting in deepest parent, write lib/* with a header
showAllLibFunctions() {
    local FILE

    if [[ -d "$1/parent" ]]; then
        showAllLibFunctions "$1/parent"
    fi

    if [[ -d "$1/lib" ]]; then
        for FILE in "$1/lib/"*; do
            if wickIsValidScript "$FILE"; then
                echo "# $FILE"
                cat "$FILE"
                echo ""
            fi
        done
    fi
}

(
    echo "#!/usr/bin/env bash"
    echo "#"
    echo "# This file was created by the wick-infect formula"
    echo ""
    echo '[ ! -z "$BASH_VERSION" ] || return 1'
    echo '[[ "$POSIXLY_CORRECT" != "y" ]] || return 1'
    echo ""
    showAllLibFunctions .
) > "$WICK_FORMULA_DIR/files/wick-infect"

wickFormula wick-base
