#!/usr/bin/env bash

wickExplorer OS wick-base os
wickExplorer ARCH wick-base arch

case "$OS" in
    centos|redhat|ubuntu)
        DIR="linux"
        ;;

    osx)
        DIR="osx"
        ;;

    *)
        DIR="UNKNOWN_OS_$OS"
esac

case "$ARCH" in
    amd64)
        DIR="${DIR}64"
        ;;

    ia32)
        DIR="${DIR}32"
        ;;

    *)
        DIR="${DIR}UNKNOWN_ARCH_$ARCH"
        ;;
esac

wickInfo "Downloading and installing jq"
wickGetUrl "http://stedolan.github.io/jq/download/$DIR/jq" /usr/bin/jq
chmod 755 /usr/bin/jq
