#!/usr/bin/env bash
# Installs [jq](http://stedolan.github.io/jq/), a command-line tool to process JSON.
#
# Examples
#
#   wickFormula jq
#
# Returns nothing.
wickExplorer os wick-base os
wickExplorer arch wick-base arch

case "$os" in
    centos|redhat|ubuntu)
        DIR="linux"
        ;;

    osx)
        DIR="osx"
        ;;

    *)
        wickError "Unknown OS: $os"
        exit 1
        ;;
esac

case "$arch" in
    amd64)
        DIR="${DIR}64"
        ;;

    ia32)
        DIR="${DIR}32"
        ;;

    *)
        wickError "Unknown architecture: $arch"
        exit 1
        ;;
esac

wickInfo "Downloading and installing jq"
wickGetUrl "http://stedolan.github.io/jq-1.5/download/$DIR/jq" /usr/bin/jq
chmod 755 /usr/bin/jq
