#!/usr/bin/env bash
# Installs [jq](http://stedolan.github.io/jq/), a command-line tool to process JSON.
#
# Examples
#
#   wickFormula jq
#
# Returns nothing.
declare arch os

wickExplorer arch wick-base arch
wickExplorer os wick-base os

case "$os" in
    centos|redhat|ubuntu)
        NAME="linux"
        ;;

    osx)
        NAME="osx"
        ;;

    *)
        wickError "Unknown OS: $os"
        exit 1
        ;;
esac

case "$arch" in
    amd64)
        NAME="${NAME}64"
        ;;

    ia32)
        NAME="${NAME}32"
        ;;

    *)
        wickError "Unknown architecture: $arch"
        exit 1
        ;;
esac

wickInfo "Downloading and installing jq"
wickGetUrl "https://github.com/stedolan/jq/releases/download/jq-1.5/jq-$NAME" /usr/bin/jq
chmod 755 /usr/bin/jq
