#!/usr/bin/env bash
# This formula adds a function that allows you to pull down a github repository in tar format.
#
# Usage
#
#   github-get-archive <repository> [options]
#
# Example
#
#   github-get-archive kyle-long/pyshelf --tag=v1.0 --dest=/tmp/pyshelf.tar.gz
#
#   github-get-archive kyle-long/pyshelf | tar xz
#
# Returns nothing.
exit 0
