#!/usr/bin/env bash
# This formula adds a function that allows you to pull down a github repository in tar format.
#
# Examples
#
#   github-get-archive <repository> [tag/branch] [destination] [username] [password]
#
# Returns nothing.
exit 0
