#!/usr/bin/env bash
# Deprecated functions are patched whenever possible.
#
# Read more about [deprecation](../doc/deprecated.md).

wickDeprecated() {
    eval "$1 () { wickError \"$1 is deprecated\" >&2; $2 \"\$@\"; return \$?; }"
}

# bin/
wickDeprecated wick-add-command wickAddCommand
wickDeprecated wick-explorer wickExplorer
wickDeprecated wick-find wickFind
wickDeprecated wick-formula wickFormula
wickDeprecated wick-help wickHelp
wickDeprecated wick-is-valid-script wickIsValidScript
wickDeprecated wick-load-lib wickLoadLib
wickDeprecated wick-load-role wickLoadRole
wickDeprecated wick-on-load wickOnLoad
wickDeprecated wick-run-formula wickRunFormula
wickDeprecated wick-run wickRun

# lib/
wickDeprecated wick-argument-string wickArgumentString
wickDeprecated wick-array-filter wickArrayFilter
wickDeprecated wick-array-join wickArrayJoin
wickDeprecated wick-command-exists wickCommandExists
wickDeprecated wick-debug wickDebug
wickDeprecated wick-debug-extreme wickDebugExtreme
wickDeprecated wick-error wickError
wickDeprecated wick-get-argument wickGetArgument
wickDeprecated wick-get-arguments wickGetArguments
wickDeprecated wick-get-dest wickGetDest
wickDeprecated wick-get-iface-ip wickGetIfaceIp
wickDeprecated wick-get-option wickGetOption
wickDeprecated wick-get-options wickGetOptions
wickDeprecated wick-get-url wickGetUrl
wickDeprecated wick-get-url-curl wickGetUrlCurl
wickDeprecated wick-get-url-wget wickGetUrlWget
wickDeprecated wick-in-array wickInArray
wickDeprecated wick-indirect wickIndirect
wickDeprecated wick-indirect-array wickIndirectArray
wickDeprecated wick-info wickInfo
wickDeprecated wick-log wickLog
wickDeprecated wick-on-exit wickOnExit
wickDeprecated wick-on-exit-trap wickOnExitTrap
wickDeprecated wick-port-up wickPortUp
wickDeprecated wick-prefix-lines wickPrefixLines
wickDeprecated wick-random-string wickRandomString
wickDeprecated wick-safe-variable-name wickSafeVariableName
wickDeprecated wick-strict-mode wickStrictMode
wickDeprecated wick-strict-mode-fail wickStrictModeFail
wickDeprecated wick-strict-run wickStrictRun
wickDeprecated wick-temp-dir wickTempDir
wickDeprecated wick-test-for-options wickTestForOptions
wickDeprecated wick-test-for-options-failure wickTestForOptionsFailure
wickDeprecated wick-wait-for wickWaitFor
wickDeprecated wick-warn wickWarn

# formulas/
wickDeprecated apache2-add-conf apache2AddConf
wickDeprecated apacke2-add-vhost apache2AddVhost
wickDeprecated cron-add cronAdd
wickDeprecated cron-remove cronRemove
wickDeprecated dnsmasq-add dnsmasqAdd
wickDeprecated dnsmasq-add-config dnsmasqAddConfig
wickDeprecated dnsmasq-remove dnsmasqRemove
wickDeprecated formula-template formulaTemplate
wickDeprecated formula-template-bash bashFormulaTemplate
wickDeprecated formula-template-mo moFormulaTemplate
wickDeprecated formula-template-sh shFormulaTemplate
wickDeprecated nscd-restart nscdRestart
wickDeprecated show-all-lib-functions showAllLibFunctions
wickDeprecated sysctl-set sysctlSet
wickDeprecated timezone-update-localtime timezoneUpdateLocaltime
wickDeprecated timezone-update-sysconfig-clock timezoneUpdateSysconfigClock
wickDeprecated timezone-update-sysconfig-timezone timezoneUpdateSysconfigTimezone
wickDeprecated timezone-update-timezone timezoneUpdateTimezone
wickDeprecated wick-hash wickHash
wickDeprecated wick-make-dir wickMakeDir
wickDeprecated wick-make-file wickMakeFile
wickDeprecated wick-make-user wickMakeUser
wickDeprecated wick-package wickPackage
wickDeprecated wick-package-apt wickPackageApt
wickDeprecated wick-package-yum wickPackageYum
wickDeprecated wick-service wickService
wickDeprecated wick-service-add wickServiceAdd
wickDeprecated wick-service-disable wickServiceDisable
wickDeprecated wick-service-enable wickServiceEnable
wickDeprecated wick-service-make-override wickServiceMakeOverride
wickDeprecated wick-service-override wickServiceOverride
wickDeprecated wick-service-reload wickServiceReload
wickDeprecated wick-service-restart wickServiceRestart
wickDeprecated wick-service-start wickServiceStart
wickDeprecated wick-service-stop wickServiceStop
wickDeprecated wick-set-config-line wickSetConfigLine
