#!/usr/bin/env bash
# Public: Writes an informational message to the logging system.  Informational
# messages are written to stdout unless `$WICK_LOG_QUIET` is set to a non-empty
# value.  The message is also sent to `wickLog` for possible output to a log
# file.  See `wickLog` for information regarding logfiles.  When `$WICK_COLOR`
# is set to a non-empty string, the output is also colorized.  ([Bash
# concepts](../doc/bash-concepts.md) explains stdout.)
#
# $@              - The message to write.  Arguments are joined into one line.
# $WICK_COLOR     - When set to a non-empty value, the output is colorized.
# $WICK_LOG_QUIET - When set to a non-empty value, the output is suppressed.
#
# Returns nothing.
wickInfo() (
    set +x
    # Disable debug in this function.  Note: this function uses a subshell!

    local content output

    wickArrayJoin content " " "$@"
    wickLog INFO "$content"

    if [[ -z "${WICK_LOG_QUIET-}" ]]; then
        wickPrefixLines output "INFO: " "$content"

        if [[ -n "${WICK_COLOR-}" ]]; then
            output=$'\E[32m'"$output"$'\E[0m'
        fi

        echo "$output"
    fi
)
