#!/bin/bash
#
# Adds a way to get the result status or exit code from a function while
# the rest of the code operates in strict mode (see `wick-strict-mode`).

wick-strict-run() {
    local DEST RESULT SET_OPTIONS

    DEST=$1
    shift
    SET_OPTIONS=$-
    set +eE
    "$@"
    RESULT=$?
    set -"$SET_OPTIONS"

    local "$DEST" && wick-indirect "$DEST" "$RESULT"
}
