#!/bin/bash
#
# This is a complement to `wick-parse-args` but instead of setting a lot of
# environment variables, this will parse the arguments and return just one
# of them if it was set.

wick-get-argument() {
    local NAME TARGET VALUE

    TARGET=$1
    wick-safe-variable-name NAME "$2"
    shift 2

    for ARG in "$@"; do
        case "$ARG" in
            --*)
                VALUE=true

                if [[ "$ARG" == "*" ]]; then
                    VALUE=${ARG#*=}
                    ARG=${ARG%%=*}
                fi

                wick-safe-variable-name ARG "$ARG"

                if [[ "$ARG" == "$NAME" ]]; then
                    local "$TARGET" && wick-indirect "$TARGET" "$VALUE"
                    return
                fi
                ;;

            -*)
                ARG="${ARG:1}"

                while [[ ! -z "$ARG" ]]; do
                    if [[ "${ARG:0:1}" == "$NAME" ]]; then
                        local "$TARGET" && wick-indirect "$TARGET" true
                        return
                    fi

                    ARG="${ARG:1}"
                done
                ;;
        esac
    done

    local "$TARGET" && wick-indirect "$TARGET" ""
}
