#!/usr/bin/env bash
# Determine if a variable is assigned, even if it is assigned an empty value.
#
# $1 = Variable name to check
#
# Examples
#
#   # This is a bit strange because we want error exit to work, but newer
#   # versions of bash disable it in specific contexts.
#   local result
#
#   unset missing
#   empty=""
#   wickStrictRun result wickIsVarSet missing
#
#   if [[ "$result" -eq 0 ]]; then
#       echo "This never is called."
#   fi
#
#   wickStrictRun result wickIsVarSet empty
#
#   if [[ "$result" -eq 0 ]]; then
#       echo "This is called even though $empty is set to an empty string."
#   fi
#
# Returns true if the variable is set, 1 if the variable is unset.
wickIsVarSet() {
    [[ "${!1-a}" == "${!1-b}" ]]
}
