#!/bin/bash
#
# Writes a warning to the logging system.
#
# This message always is written to stdout as well.
#
# Parameters:
#     $*: The log message to write
wick-warn() (
    set +x
    local OUTPUT

    wick-log "WARN" "$*"
    wick-prefix-lines OUTPUT "WARN: " "$*"

    if [[ ! -z "${WICK_COLOR-}" ]]; then
        OUTPUT=$'\E[33;1m'"$OUTPUT"$'\E[0m'
    fi

    echo "$OUTPUT"
)
