#!/bin/bash

wick-array-filter() {
    local FILTER RESULT TARGET

    TARGET=$1
    FILTER=$2
    RESULT=()
    shift 2

    while [[ $# -gt 0 ]]; do
        if "$FILTER" "$1"; then
            RESULT[${#RESULT[@]}]=$1
        fi

        shift
    done

    if [[ ${#RESULT[@]} -eq 0 ]]; then
        local "$TARGET" && wick-indirect-array "$TARGET"
        return
    fi

    local "$TARGET" && wick-indirect-array "$TARGET" "${RESULT[@]}"
}
