#!/bin/bash

wick-get-options() {
    local OPTIONS PREFIX TARGET

    OPTIONS=()
    TARGET=$1
    PREFIX="-"
    shift

    while [[ $# -gt 0 ]]; do
        if [[ "${1:0:1}" == "$PREFIX" ]]; then
            if [[ "$1" == "--" ]]; then
                PREFIX="DO NOT MATCH"
            else
                OPTIONS[${#OPTIONS[@]}]=$1
            fi
        fi

        shift
    done

    if [[ "${#OPTIONS[@]}" -eq 0 ]]; then
        local "$TARGET" && wick-indirect-array "$TARGET"
        return
    fi

    local "$TARGET" && wick-indirect-array "$TARGET" "${OPTIONS[@]}"
}
