#!/bin/bash

wick-get-arguments() {
    local ARGS PREFIX TARGET

    ARGS=()
    TARGET=$1
    PREFIX="-"
    shift

    while [[ $# -gt 0 ]]; do
        if [[ "${1:0:1}" != "$PREFIX" ]]; then
            ARGS=("${ARGS[@]}" "$1")
        else
            if [[ "$1" == "--" ]]; then
                PREFIX="DO NOT MATCH"
            fi
        fi

        shift
    done

    local "$TARGET" && wick-indirect-array "$TARGET" "${ARGS[@]}"
}
