#!/usr/bin/env bash
# Internal: Download a file with curl.
#
# $DEST     - Destination filename or empty string for stdout.
# $PROGRESS - Show progress bar when not an empty string.
# $TIMEOUT  - Limit the command to run for the given number of seconds when
#             this is not an empty string.
# $URL      - The URL to download.
#
# Returns non-zero on error.
wickGetUrlCurl() {
    local ARGS

    ARGS=(curl -L -f)

    if [[ -z "$PROGRESS" ]]; then
        ARGS[${#ARGS[@]}]="-s"
    fi

    if [[ ! -z "$TIMEOUT" ]]; then
        ARGS[${#ARGS[@]}]="-m"
        ARGS[${#ARGS[@]}]=$TIMEOUT
    fi

    if [[ ! -z "$DEST" ]]; then
        ARGS[${#ARGS[@]}]="-o"
        ARGS[${#ARGS[@]}]=$DEST
    fi

    ARGS[${#ARGS[@]}]=$URL
    wickDebug "wickGetUrl:" "${ARGS[@]}"
    "${ARGS[@]}"
}
