#!/usr/bin/env bash
# Public: Grab all non-option arguments and return them as an array.
#
# $1   - Name of variable that should receive the result.
# $2-@ - Command line arguments to parse.  Typically this is `"$@"`.
#
# Significantly better examples are explained in
# [argument processing](../doc/argument-processing.md).
#
# Examples
#
#   # Any non-option arguments are placed into $arguments.
#   # If there were none, $arguments is set to an empty list.
#   wickGetArguments arguments "$@"
#
# Returns nothing.
wickGetArguments() {
    local args prefix target

    args=()
    target=$1
    prefix="-"
    shift

    while [[ $# -gt 0 ]]; do
        if [[ "${1:0:1}" != "$prefix" ]]; then
            args[${#args[@]}]=$1
        else
            if [[ "$1" == "--" ]]; then
                prefix="DO NOT MATCH"
            fi
        fi

        shift
    done

    # shellcheck disable=SC2068
    local "$target" && wickIndirectArray "$target" ${args[@]+"${args[@]}"}
}
