#!/bin/bash

wick-array-append() {
    local LEN NAME VALUE

    NAME="$1"
    shift

    while [[ $# -gt 0 ]]; do
        eval "LEN=\${#${NAME}[@]}"
        wick-argument-string VALUE "$1"
        eval "$NAME[$LEN]=$VALUE"
        shift
    done
}
