#!/bin/bash
#
# Writes an error message to the logging system.
#
# This message is always written to stderr.
#
# Parameters:
#     $*: The log message to write
wick-error() (
    set +x
    local OUTPUT

    wick-log "ERROR" "$*"
    wick-prefix-lines OUTPUT "ERROR: " "$*"
    echo "$OUTPUT" >&2
)
