#!/usr/bin/env bash
# Internal: Download a file with curl.
#
# $DEST     - Destination filename or empty string for stdout.
# $PROGRESS - Show progress bar when not an empty string.
# $TIMEOUT  - Limit the command to run for the given number of seconds when
#             this is not an empty string.
# $URL      - The URL to download.
# $USERNAME - Username to use for authentication.
# $PASSWORD - Password to use for authentication.
#
# Returns non-zero on error.
wickGetUrlWget() {
    local args redact redactedArgs

    args=(wget)

    if [[ -z "$PROGRESS" ]]; then
        args[${#args[@]}]="--quiet"
    fi

    if [[ -n "$TIMEOUT" ]]; then
        args[${#args[@]}]="--timeout"
        args[${#args[@]}]="$TIMEOUT"
    fi

    if [[ -n "$DEST" ]]; then
        args[${#args[@]}]="-O"
        args[${#args[@]}]="$DEST"
    fi

    if [[ -n "$USERNAME" ]]; then
        args[${#args[@]}]="--user"
        args[${#args[@]}]="$USERNAME"
    fi

    if [[ -n "$PASSWORD" ]]; then
        args[${#args[@]}]="--password"
        redact="${#args[@]}"
        args[${#args[@]}]="$PASSWORD"
    fi

    args[${#args[@]}]=$URL

    #: Redacting password from debug log
    redactedArgs=("${args[@]}")

    if [[ -n "$PASSWORD" ]]; then
        redactedArgs["$redact"]=XXXXXXX
    fi

    wickDebug "wickGetUrl:" "${redactedArgs[@]}"
    "${args[@]}"
}
