#!/usr/bin/env bash
# Internal: Default failure reporter function for `wickTestForOptions`.
#
# $1       - Option that was not specified.  This is without the double-hyphens.
# $FORMULA - Set by [`wick`](../bin/wick) when running a formula.
# $ROLE    - Set by [`wick`](../bin/wick) when running a role.
#
# Returns nothing.
wickTestForOptionsFailure() {
    if [[ -n "${FORMULA-}" ]]; then
        wickError "Formula $FORMULA requires option: --$1" || return 1
    else
        if [[ -n "${ROLE-}" ]]; then
            wickError "Role $ROLE requires option: --$1" || return 1
        else
            wickError "Missing required option:  --$1" || return 1
        fi
    fi
}
