#!/usr/bin/env bash
# Enables [strict mode] for Bash, based off [unofficial bash strict mode].
# Errors will kill the program.  Accessing undefined variables will cause
# errors (and exit the program).  Commands in pipelines that return a non-zero
# status code will also cause errors and kill the program.  An ERR trap is also
# enabled that will produce a stack trace when errors happen.
#
# This is intended to be used at the beginning of your shell scripts in order
# to ensure correctness in your programming.
#
# Please check out the detailed explanation of [strict mode] for further
# information.
#
# Examples
#
#   #!/usr/bin/env bash
#   . /usr/local/lib/wick-infect
#   wickStrictMode
#
# [unofficial bash strict mode]: http://redsymbol.net/articles/unofficial-bash-strict-mode/
#
# [strict mode]: ../doc/bash-strict-mode.md
#
# Returns nothing.
wickStrictMode() {
    set -eEu -o pipefail
    shopt -s extdebug
    IFS=$'\n\t'
    trap 'wickStrictModeFail $?' ERR
}
