#!/bin/bash

wick-test-for-arguments() {
    local ARG FAILURE_CMD RESULT SEEKING VALUE

    SEEKING=()
    RESULT=0
    FAILURE_CMD=${WICK_TEST_FOR_ARGUMENTS_FAILURE:-wick-test-for-arguments-failure}

    while [[ ! -z "$1" ]] && [[ "$1" != "--" ]]; do
        SEEKING=("${SEEKING[@]}" "$1")
        shift
    done

    shift

    for ARG in "${SEEKING[@]}"; do
        VALUE=""
        wick-get-argument VALUE "$ARG" "$@"

        if [[ -z "$VALUE" ]]; then
            "$FAILURE_CMD" "$ARG"
            RESULT=1
        fi
    done

    return $RESULT
}

wick-test-for-arguments-failure() {
    if [[ ! -z "$FORMULA" ]]; then
        wick-error "Formula $FORMULA requires argument: --$ARG"
    else
        wick-error "Role $ROLE requires argument: --$ARG"
    fi
}
