#!/usr/bin/env bash
# Public: Download a URL, writing it to stdout or optionally saving it to a
# file.  Uses `curl` or `wget` if installed on the system.
#
# $1                - URL to download.
# $2                - Optional, filename to write with the resulting content.
#                     When not specified, this writes to stdout.
# --progress        - Show progress information during downloads.
# --timeout=SECONDS - Give up after this many seconds elapse.
#
# Examples
#
#   # Download shell script execute it
#   wickGetUrl --timeout=30 https://get.rvm.io/ | bash
#
#   # Download a large file and show progress information
#   wickGetUrl --progress http://example.com/large-file.tar.gz /tmp/large-file.tgz
#
# Returns zero on success, non-zero if there is an error downloading.
wickGetUrl() {
    # These variables are intended to be used outside of wickGetUrl
    # by the child functions for each command, thus they should be
    # capitalized.
    local DEST PROGRESS TIMEOUT URL

    wickGetOption PROGRESS progress "$@"
    wickGetOption TIMEOUT timeout "$@"
    wickGetArgument URL 0 "$@"
    wickGetArgument DEST 1 "$@"
    wickDebug "wickGetUrl url: $URL"
    wickDebug "wickGetUrl dest: $DEST"

    if wickCommandExists curl; then
        wickGetUrlCurl || return 1
        return 0
    fi

    if wickCommandExists wget; then
        wickGetUrlWget || return 1
        return 0
    fi

    wickError "Unable to download url - no suitable programs found"
    return 1
}
