#!/usr/bin/env bash
# Public: Runs a command and captures its return code, even when [strict mode]
# is enabled.  The variable name you specify is set to the return code of the
# command.
#
# $1   - Name of variable that should get the return value / status code.
# $2-@ - Command and arguments to run.
#
# This is intended to be used along with `wickStrictMode`.
#
# Example:
#
#   #!/usr/bin/env bash
#   . /usr/local/lib/wick-infect
#   wickStrictMode
#
#   wickStrictRun result grep "some-string" /etc/some-file.cfg > /dev/null 2>&1
#
#   if [[ $result -eq 0 ]]; then
#       wickInfo "some-string was found"
#   else
#       wickInfo "some-string was not found"
#   fi
#
# Returns nothing.
wickStrictRun() {
    local dest result setOptions

    dest=$1
    shift
    setOptions=$-
    set +eE
    "$@"
    result=$?
    set -"$setOptions"

    local "$dest" && wickIndirect "$dest" "$result"
}
