#!/usr/bin/env bash
# Public: Creates a temporary directory.  Automatically sets up a hook with
# `wickOnExit` to delete the directory when the shell script is finished.
#
# $1 - Name of variable that will receive the path of the newly created
#      temporary directory.
#
# Examples
#
#   wickTempDir TEMPDIR
#   (
#       cd TEMPDIR
#       wickGetUrl http://install.example.com/ installer-script
#       . installer-script
#   )
#
#   # Directory is automatically removed for you after this script.
#
# Returns nothing.
wickTempDir() {
    local BASE DIR

    BASE="/tmp"

    if [ ! -z "${TMPDIR:-}" ] && [ -d "$TMPDIR" ]; then
        BASE="$TMPDIR"
    fi

    BASE="${BASE}/wick."

    while true; do
        wickRandomString DIR 16
        DIR="$BASE$DIR"

        if [ ! -e "$DIR" ]; then
            if mkdir -m 0700 "$DIR" 2>/dev/null; then
                wickDebug "Temporary directory created: $DIR"
                wickOnExit rm -rf "$DIR"
                local "$1" && wickIndirect "$1" "$DIR"
                return 0
            else
                wickDebug "Temporary directory could not be created: $DIR"
            fi
        else
            wickDebug "Temporary directory already exists: $DIR"
        fi
    done
}
