#!/usr/bin/env bash
# Public: Determines the IP address associated with a given network interface.
# If no interface is provided, this returns the first IP address listed by
# `ifconfig`.
#
# $1 - Name of the variable that should receive the result.
# $2 - Optional, network interface name.  If not specified, defaults to the
#      first one returned by `ifconfig`.
#
# Examples
#
#   local ip
#
#   if ! wickGetIfaceIp ip tun0; then
#       echo "Tunnel is not yet established"
#       exit 1
#   fi
#
#   echo "Tunnel IP:  $ip"
#
# Returns 0 on success, non-zero on failure.
wickGetIfaceIp() {
    local ip list

    if [[ "$2" == '*' ]]; then
        list=()

        while read ip; do
            ip=${ip#*inet addr:}
            ip=${ip#*inet }
            ip=${ip%% *}
            list[${#list[@]}]=$ip
        done < <(ifconfig -v 2>/dev/null | grep 'inet ' || echo "")

        if [[ ${#list[@]} -eq 0 ]]; then
            local "$1" && wickIndirectArray "$1"
            return 0
        fi

        local "$1" && wickIndirectArray "$1" "${list[@]}"
        return 0
    fi

    ip=$(ifconfig -v $2 2>/dev/null | grep inet\ | head -n 1 || echo "")
    ip=${ip#*inet addr:}
    ip=${ip#*inet }
    ip=${ip%% *}

    if [[ -z "$ip" ]]; then
        return 1
    fi

    local "$1" && wickIndirect "$1" "$ip"
}

