#!/bin/bash
#
# Enable extreme debug logging

wick-debug-extreme() {
    if [[ $# -eq 0 ]] || [[ "$1" != "stop" ]]; then
        export PS4='+\$?:$? (${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): } $BASH_COMMAND\n -> '
        set -x
    else
        set +x
    fi
}
