#!/usr/bin/env bash
# Public: Combine an array of strings together into one string.
#
# $1   - Name of variable that should get the result.
# $2   - String to use for joining elements in the array.
# $3-@ - Array values.
#
# Examples
#
#   arr=(one two "three four" five)
#   wickArrayJoin dest "+" "${arr[@]}"
#
#   # Result: one+two+three four+five
#   echo "$dest"
#
# Returns nothing.
wickArrayJoin() {
    local joiner result target

    target=${1-}
    joiner=${2-}
    result=""
    shift 2

    if [[ $# -gt 0 ]]; then
        result="$1"
        shift
    fi

    while [[ $# -gt 0 ]]; do
        result="$result$joiner$1"
        shift
    done

    local "$target" && wickIndirect "$target" "$result"
}
