#!/usr/bin/env bash
# Public: Change a variable so it is a valid variable in bash.  This is used
# primarily by argument parsing functions.
#
# $1 - Name of variable that should receive the altered string.
# $2 - The string we are making safe.
#
# You can't set things like `$ABC-DEF` as a variable easily and so this
# function will turn that into something that could be an environment variable
# by replacing illegal characters with an underscore.
#
# Examples
#
#   wick-safe-variable-name fixed "ABC-DEF"
#   echo "$fixed"  # Outputs "ABC_DEF"
#
# Returns nothing.
wickSafeVariableName() {
    local safe

    safe=${2//-/_}
    safe=${safe// /_}
    local "$1" && wickIndirect "$1" "$safe"
}
