#!/usr/bin/env bash
# Public: Creates a temporary directory.  Automatically sets up a hook with
# `wickOnExit` to delete the directory when the shell script is finished.
#
# $1 - Name of variable that will receive the path of the newly created
#      temporary directory.
#
# Examples
#
#   wickTempDir tempdir
#   (
#       cd tempdir
#       wickGetUrl http://install.example.com/ installer-script
#       . installer-script
#   )
#
#   # Directory is automatically removed for you after this script.
#
# Returns nothing.
wickTempDir() {
    local base dir

    base="/tmp"

    if [ ! -z "${TMPdir:-}" ] && [ -d "$TMPdir" ]; then
        base="$TMPdir"
    fi

    base="${base}/wick."

    while true; do
        wickRandomString dir 16
        dir="$base$dir"

        if [ ! -e "$dir" ]; then
            if mkdir -m 0700 "$dir" 2>/dev/null; then
                wickDebug "Temporary directory created: $dir"
                wickOnExit rm -rf "$dir"
                local "$1" && wickIndirect "$1" "$dir"
                return 0
            fi

            wickDebug "Temporary directory could not be created: $dir"
        else
            wickDebug "Temporary directory already exists: $dir"
        fi
    done
}
