#!/usr/bin/env bash
# Public: Logging function for errors.  Use this to log error messages right
# before you exit the program or return a failure.  All messages are written to
# stderr.  Log messages are also passed to the `wickLog` function to be logged
# to a file.  (See `wickLog` for information about log files.  See
# [Bash concepts](../doc/bash-concepts.md) for more about stderr.) This also
# will colorize the output when the `WICK_COLOR` environment variable is set to
# a non-empty string.
#
# $@          - The message to log.  Arguments are joined into one line.
# $WICK_COLOR - Colorizes output when set to a non-empty string.
#
# Examples
#
#    wickError "Could not find some vital thing"
#
#    exit 1
#
# Returns nothing.
wickError() {
    (
        set +x
        # Disable debug in this function.  Note: this function uses a subshell!

        local content output

        wickArrayJoin content " " "$@" || return $?
        wickLog "ERROR" "$content" || return $?
        wickPrefixLines output "ERROR: " "$content" || return $?

        if [[ -n "${WICK_COLOR-}" ]]; then
            output=$'\E[41;37;1m'"$output"$'\E[0m'
        fi

        echo "$output" >&2
    )
}
