#!/usr/bin/env bash
# Internal: Download a file with curl.
#
# $DEST     - Destination filename or empty string for stdout.
# $PROGRESS - Show progress bar when not an empty string.
# $TIMEOUT  - Limit the command to run for the given number of seconds when
#             this is not an empty string.
# $URL      - The URL to download.
# $USERNAME - Username to use for authentication.
# $PASSWORD - Password to use for authentication.
#
# Returns non-zero on error.
wickGetUrlCurl() {
    local args redact redactedArgs

    args=(curl -L -f)

    if [[ -z "$PROGRESS" ]]; then
        args[${#args[@]}]="-s"
    fi

    if [[ -n "$TIMEOUT" ]]; then
        args[${#args[@]}]="-m"
        args[${#args[@]}]="$TIMEOUT"
    fi

    if [[ -n "$DEST" ]]; then
        args[${#args[@]}]="-o"
        args[${#args[@]}]="$DEST"
    fi

    if [[ -n "$USERNAME" ]]; then
        args[${#args[@]}]="--user"
        redact="${#args[@]}"
        args[${#args[@]}]="$USERNAME:$PASSWORD"
    fi

    args[${#args[@]}]=$URL

    #: Redacting password from debug log
    redactedArgs=("${args[@]}")

    if [[ -n "$USERNAME" ]]; then
        redactedArgs["$redact"]="$USERNAME:XXXXXXX"
    fi

    wickDebug "wickGetUrl:" "${redactedArgs[@]}" || return $?
    "${args[@]}"
}
