#!/usr/bin/env bash
# Public: Logging for warnings, such as when problems are detected and they
# aren't severe enough to warrant an error and termination of the function.
# Warning messages are always written to stderr.  See `wickLog` for information
# about writing log messages to files.  This also colorizes the output when
# `$WICK_COLOR` is set to a non-empty value.  (See
# [Bash concepts](../doc/bash-concepts.md) regarding stderr.)
#
# $@          - The text to log.  Arguments are appended into a single line.
# $WICK_COLOR - When set to a non-empty string the output is colorized.
#
# Examples
#
#   if [[ -f /some/file ]]; then
#       wickWarn "File exists when it should not."
#       rm /some/file
#   fi
#
# Returns nothing.
wickWarn() {
    (
        set +x
        # Disable debug in this function.  Note: this function uses a subshell!

        local content output

        wickArrayJoin content " " "$@" || return $?
        wickLog "WARN" "$content" || return $?
        wickPrefixLines output "WARN: " "$content" || return $?

        if [[ -n "${WICK_COLOR-}" ]]; then
            output=$'\E[33;1m'"$output"$'\E[0m'
        fi

        echo "$output" >&2
    )
}
