#!/bin/bash

wick-parse-arguments() {
    local ARG LEN UNPARSED UNPARSED_DEST VALUE

    UNPARSED_DEST="$1"
    shift
    UNPARSED=()
    LEN=0

    for ARG in "$@"; do
        case "$ARG" in
            --*)
                VALUE=true

                if [[ "$ARG" == *=* ]]; then
                    VALUE=${ARG#*=}
                    ARG=${ARG%%=*}
                fi

                wick-safe-variable-name ARG "$ARG"
                printf -v "ARGS_${ARG:2}" '%s' "$VALUE"
                ;;

            -*)
                ARG="${ARG:1}"

                while [[ ! -z "$ARG" ]]; do
                    printf -v "ARGS_${ARG:0:1}" 'true'
                    ARG="${ARG:1}"
                done
                ;;

            *)
                UNPARSED[$LEN]="$ARG"
                LEN=$(($LEN + 1))
                ;;
        esac
    done

    local "$UNPARSED_DEST" && wick-indirect-array "$UNPARSED_DEST" "${UNPARSED[@]}"
}
