#!/bin/bash

WICK_ON_EXIT_ITEMS=()

wick-on-exit() {
    local COMMAND LEN NAME

    NAME="WICK_ON_EXIT_$BASHPID"
    eval "LEN=\${#$NAME[@]}"
    printf -v COMMAND " %q" "$@"
    wick-debug "Adding wick-on-exit item [$BASHPID $LEN]: ${COMMAND:1}"
    eval "$NAME=(\"\${$NAME[@]}\" \"\${COMMAND:1}\")"

    # Always set or reset the trap
    trap wick-on-exit-trap EXIT
}

wick-on-exit-trap() {
    local CMD ITEM_ARRAY

    ITEM_ARRAY="WICK_ON_EXIT_$BASHPID[@]"
    wick-debug "Running wick-on-exit trap [$BASHPID]"

    for CMD in "${!ITEM_ARRAY}"; do
        wick-debug "Running wick-on-exit command: $CMD"
        eval $CMD
    done

    wick-debug "Done running wick-on-exit traps"
}
