#!/usr/bin/env bash
# Public: Convert a string into a safely quoted string that's safe to pass
# around as an argument.  It is unlikely that this will be necessary for most
# scripting that's performed because one would need to use `eval` to parse this
# back to the original value.
#
# $1   - Name of the environment variable that should get the result.
# $2-@ - The value to escape.
#
# Examples
#
#   wickArgumentString exampleResult one two three "four five"
#   set | fgrep "exampleResult"
#   # Output:
#   # exampleResult='one two three four\ five'
#
# Returns nothing.
wickArgumentString() {
    local escaped target

    target="$1"
    shift
    printf -v escaped " %q" "$@" || return $?

    local "$target" && wickIndirect "$target" "${escaped:1}"
}

