#!/bin/bash

wick-wait-for() {
    local LATCH_PROCESS RESULT SLEEP_PROCESS SLEEP_TIME

    # Run everything in a subshell to automatically enable monitor mode (set +m)
    (
        # Process 1 - the timeout
        SLEEP_TIME=$1
        shift
        (
            sleep $SLEEP_TIME
            exit 127
        ) > /dev/null 2>&1 &
        SLEEP_PROCESS=$!

        # Process 2 - the latch
        (
            while ! ${1+"$@"}; do
                echo "latch fail"
                sleep 1
            done
            echo "latch success"
        ) > /dev/null 2>&1 &
        LATCH_PROCESS=$!

        # Delay until one of the processes finish
        wait -n $SLEEP_PROCESS $LATCH_PROCESS
        RESULT=$?

        # Clean up and hide the "Terminated" message from killing bash
        kill $SLEEP_PROCESS $LATCH_PROCESS > /dev/null 2>&1
        wait $SLEEP_PROCESS $LATCH_PROCESS > /dev/null 2>&1
    )

    return $RESULT
}
