#!/usr/bin/env bash
# Updates all packages on the system except kernel updates.
#
# For RedHat and CentOS this will skip kernel updates because that may
# unintentionally break the guest additions when the machine is under
# VirtualBox or another virtualization system.
#
# When guest additions are installed and the kernel is updated, it appears
# that one must also reboot and then recompile the guest additions against
# the updated headers in order for things to work.  To avoid that problem
# we just skip the kernel packages.
#
# Examples
#
#   wickFormula update-packages
#
# Returns nothing.
wickInfo "Updating all packages except the kernel"
wickExplorer OS wick-base os

case "$OS" in
    redhat|centos)
        yum --exclude=kernel* update -y
        ;;

    debian|ubuntu)
        tryNumber=0

        while [[ "$tryNumber" -lt 3 ]]; do
            tryNumber=$((tryNumber + 1))
            wickInfo "Attempting update (try $tryNumber of 3)"

            if ! wickWaitFor 600 wickIsAptAvailable; then
                wickError "Apt stayed locked for more than 600 seconds. Aborting."

                exit 1
            fi

            if apt-get update; then
                tryNumber=100
            fi
        done

        tryNumber=0

        while [[ "$tryNumber" -lt 3 ]]; do
            tryNumber=$((tryNumber + 1))
            wickInfo "Attempting upgrade (try $tryNumber of 3)"

            if ! wickWaitFor 600 wickIsAptAvailable; then
                wickError "Apt stayed locked for more than 600 seconds. Aborting."

                exit 1
            fi

            if DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::="--force-confdef" apt-get upgrade -y; then
                tryNumber=100
            fi
        done
        ;;

    *)
        wickError "Unknown package manager for OS:  $OS"
        ;;
esac
