#!/usr/bin/env bash
cat <<'EOF'
Routing tables

Internet:
Destination        Gateway            Flags        Refs      Use   Netif Expire
0/1                10.1.11.5          UGSc            0        0   utun2
default            192.168.1.1        UGSc            1        0     en0
default            10.1.11.5          UGScI          14        0   utun2
10.1.11.1/32       10.1.11.5          UGSc            0        0   utun2
10.1.11.5          10.1.11.6          UHr            22        0   utun2
10.1.11.5/32       link#14            UCS             0        0   utun2
14.2.13.75/32      192.168.1.1        UGSc            1        0     en0
127                127.0.0.1          UCS             0        0     lo0
127.0.0.1          127.0.0.1          UH             89 16338107     lo0
128.0/1            10.1.11.5          UGSc            4        0   utun2
169.254            link#4             UCS             0        0     en0
192.168.1          link#4             UCS             2        0     en0
192.168.1.1/32     link#4             UCS             1        0     en0
192.168.1.1        dc:ef:9:b3:a4:f0   UHLWIir         4       97     en0   1110
192.168.1.4        68:37:e9:68:59:65  UHLWI           0      117     en0    866
192.168.1.5        a0:ed:cd:7c:77:71  UHLWI           0        0     en0    192
192.168.1.10/32    link#4             UCS             0        0     en0
224.0.0/4          link#4             UmCS            2        0     en0
224.0.0/4          link#14            UmCSI           0        0   utun2
224.0.0.251        1:0:5e:0:0:fb      UHmLWI          0        0     en0
239.255.255.250    1:0:5e:7f:ff:fa    UHmLWI          0      221     en0
255.255.255.255/32 link#4             UCS             1        0     en0
255.255.255.255    c:89:10:17:d:93    UHLWbI          0        0     en0   1110
255.255.255.255/32 link#14            UCSI            0        0   utun2

Internet6:
Destination                             Gateway                         Flags         Netif Expire
default                                 fe80::%utun0                    UGcI          utun0
default                                 fe80::%utun1                    UGcI          utun1
::1                                     ::1                             UHL             lo0
fe80::%lo0/64                           fe80::1%lo0                     UcI             lo0
fe80::1%lo0                             link#1                          UHLI            lo0
fe80::%awdl0/64                         link#8                          UCI           awdl0
fe80::d061:41ff:fe02:c5eb%awdl0         d2:61:41:2:c5:eb                UHLI            lo0
fe80::%utun0/64                         fe80::4686:1f38:ae0a:fe12%utun0 UcI           utun0
fe80::4686:1f38:ae0a:fe12%utun0         link#10                         UHLI            lo0
fe80::%utun1/64                         fe80::623e:4228:c317:8bd5%utun1 UcI           utun1
fe80::623e:4228:c317:8bd5%utun1         link#11                         UHLI            lo0
ff01::%lo0/32                           ::1                             UmCI            lo0
ff01::%awdl0/32                         link#8                          UmCI          awdl0
ff01::%utun0/32                         fe80::4686:1f38:ae0a:fe12%utun0 UmCI          utun0
ff01::%utun1/32                         fe80::623e:4228:c317:8bd5%utun1 UmCI          utun1
ff02::%lo0/32                           ::1                             UmCI            lo0
ff02::%awdl0/32                         link#8                          UmCI          awdl0
ff02::%utun0/32                         fe80::4686:1f38:ae0a:fe12%utun0 UmCI          utun0
ff02::%utun1/32                         fe80::623e:4228:c317:8bd5%utun1 UmCI          utun1
EOF
