#!/usr/bin/env bash
# Function retrieves GitHub repository as a tarball.
#
# $1              - Path to GitHub repository.
# $2              - Destination of tarball. Output to stdout if no destination given.
# --tag=TAG       - Tag name or branch to pull from. Defaults to master.
# --username=USER - Username for private GitHub repositories.
# --password=PASS - Password for private GitHub repositories.
#
# Examples
#
#   # Retrieves a tarball of kyle-long/pyshelf repository from tag v1.0
#   # and outputs it to /tmp/pyshelf.tar.gz
#   githubGetArchive kyle-long/pyshelf --tag=v1.0 --dest=/tmp/pyshelf.tar.gz
#
#   # Retrieves a tarball of kyle-long/pyshelf and outputs it to stdout
#   # which can be piped into tar.
#   githubGetArchive kyle-long/pyshelf | tar xz
#
# Returns zero on success, non-zero if there is an error downloading or a missing argument.
githubGetArchive() {
    local args destination password repository tag username

    wickGetArgument repository 0 "$@"
    wickGetArgument destination 1 "$@"
    wickGetOption tag tag "$@"
    wickGetOption username username "$@"
    wickGetOption password password "$@"
    : "${tag:=master}"

    if [[ -z "$repository" ]]; then
        wickError "Missing argument. Please provide a repository."

        return 1
    fi

    if [[ -n "$username" ]]; then
        args[${#args[@]}]="--user"
        args[${#args[@]}]="$username:$password"
    fi

    if [[ "${destination:--}" != "-" ]]; then
        args[${#args[@]}]="-o"
        args[${#args[@]}]="$destination"
    fi

    wickGetUrl "https://github.com/$repository/tarball/$tag" "$destination" --username="$username" --password="$password"
}
