#!/usr/bin/env bash
# Determines the erlang package based on the OS distribution.
#
# Examples
#
#   wickFormula erlang
#
# Returns nothing.
declare os

wickExplorer os wick-base os

case "$os" in
    debian|ubuntu)
        wickPackage erlang-nox
        ;;

    *)
        wickPackage erlang
        ;;
esac
