#!/usr/bin/env bash

# There are many other settings you can tweak for better performance.  Each
# one should be tested to determine if they are applicable to the situation.
# http://shokunin.co/blog/2014/11/11/operational_redis.html
wickInfo "Installing redis"
sysctl-set vm.overcommit_memory 1
sysctl-set net.core.somaxconn 512
YUM_ENABLE_REPO=remi wickPackage redis

# Listen on all interfaces
sed -i 's/^bind/#bind/' /etc/redis.conf

wickService restart redis
wickService enable redis
