#!/usr/bin/env bash
# Installs redis onto the box.
#
# There are many other settings you can tweak for better performance beyond
# what this formula set.  Each one should be tested to determine if they are
# applicable to the situation.
# http://shokunin.co/blog/2014/11/11/operational_redis.html
#
# Examples
#
#   wickFormula redis
#
# Returns nothing.
wickInfo "Installing redis"
sysctlSet vm.overcommit_memory 1
sysctlSet net.core.somaxconn 512
YUM_ENABLE_REPO=remi wickPackage redis

# Listen on all interfaces
sed -i 's/^bind/#bind/' /etc/redis.conf

wickService restart redis
wickService enable redis
