#!/usr/bin/env bash
# Installs redis onto the box.
#
# --password=PASS - Sets a password for this redis installation
#
# There are many other settings you can tweak for better performance beyond
# what this formula set.  Each one should be tested to determine if they are
# applicable to the situation.
# http://shokunin.co/blog/2014/11/11/operational_redis.html
#
# Examples
#
#   wickFormula redis
#
#   wickFormula redis --password="A very long password goes here"
#
# Returns nothing.
wickInfo "Installing redis"
wickGetArgument password password "$@"
sysctlSet vm.overcommit_memory 1
sysctlSet net.core.somaxconn 512
YUM_ENABLE_REPO=remi wickPackage redis

# Listen on all interfaces
sed -i 's/^bind/#bind/' /etc/redis.conf

# Set or clear a password
if [[ -z "$password" ]]; then
    sed -i '/^requirepass/d' /etc/redis.conf
else
    wickSetConfigLine /etc/redis.conf "requirepass \"$password\""
fi

wickService restart redis
wickService enable redis
