#!/bin/bash

apache2-add-conf() {
    local CONF OPTIONS OS

    wick-get-argument CONF 0 "$@"
    wick-get-options OPTIONS "$@"
    wick-info "Adding Apache2 config: ${OPTIONS[@]} $CONF"
    wick-explorer OS wick-base os

    case "$OS" in
        redhat|centos)
            wick-make-file "${OPTIONS[@]}" /etc/httpd/conf.d/
            wick-service reload httpd
            ;;

        *)
            wick-make-file "${OPTIONS[@]}" /etc/apache2/conf-available
            a2enconf "$CONF"
            wick-service reload apache2
            ;;
    esac
}
