#!/usr/bin/env bash
# Installs a configuration file and reloads Apache.  See `wickMakeFile` in
# [wick-base](../wick-base) for information regarding paths and further
# options.
#
# $1 - Name of file contained in the formula to add as a configuration file
#      for Apache.
# $@ - All other options pass directly to `wickMakeFile`.
#
# Returns nothing.
apache2AddConf() {
    local conf options os

    wickGetArgument conf 0 "$@"
    wickGetOptions options "$@"
    wickInfo "Adding Apache2 config:" "${options[@]-}" "$conf"
    wickExplorer os wick-base os

    case "$os" in
        redhat|centos)
            wickMakeFile "${options[@]-}" /etc/httpd/conf.d/
            wickService reload httpd
            ;;

        *)
            wickMakeFile "${options[@]-}" /etc/apache2/conf-available
            a2enconf "$conf"
            wickService reload apache2
            ;;
    esac
}
