#!/usr/bin/env bash
# Installs a virtual host and reloads Apache.  See `wickMakeFile` in
# [wick-base](../wick-base) for information regarding paths and further
# options.
#
# $1 - Name of file contained in the formula to add as a virtual host for
#      Apache.
# $@ - All other options pass directly to `wickMakeFile`.
#
# Returns nothing.
apache2AddVhost() {
    local options os site

    wickGetArgument site 0 "$@"
    wickGetOptions options "$@"
    wickInfo "Adding Apache2 vhost:" "${options[@]-}" "$site"
    wickExplorer os wick-base os

    case "$os" in
        redhat|centos)
            wickMakeFile "${options[@]-}" /etc/httpd/conf.d/
            wickService reload httpd
            ;;

        *)
            wickMakeFile "${options[@]-}" /etc/apache2/sites-available
            a2ensite "$site"
            wickService reload apache2
            ;;
    esac
}
