#!/usr/bin/env bash
# Installs the requirements that most init scripts depend upon without
# including many unnecessary dependencies.
#
# Examples
#
#   wickFormula redhat-lsb-core
#
# Returns nothing.
wickInfo "Installing redhat-lsb-core"
wickPackage redhat-lsb-core
