#!/usr/bin/env bash
# Alters the SSH server's settings.
#
# --agent-forwarding[=no] - Allow/deny agent forwarding.
# --faster-login          - Enables faster login (disable DNS and GSSAPI).
#                           Same as using `--use-dns=no --gssapi-auth=no`
# --gssapi-auth[=no]      - Enable/disable GSSAPI authentication.
# --password-auth[=no]    - Allow/deny password authentication mechanisms.
# --use-dns[=no]          - Enable/disable DNS
#
# For `=no`, that means it is optional.  The default is to enable the
# option.  You turn off the option by using "no" and turn on the option by not
# specifying a value.  See the examples for more information.
#
# Each of these options will toggle one setting in the config file, unless
# otherwise noted.
#
# If there were any changes to the file, sshd is reloaded.
#
# Examples
#
#   # Faster logins
#   wickFormula sshd-tweak --faster-login
#
#   # Same as above
#   wickFormula sshd-tweak --use-dns=no --gssapi-auth=no
#
#   # Enable agent forwarding and disable passwords
#   wickFormula sshd-tweak --agent-forwarding --password-auth=no
#
# Returns nothing.
declare config fasterLogin hashAfter hashBefore osType result

config="/etc/ssh/sshd_config"
serviceName=sshd

wickGetOption fasterLogin --faster-login "$@"
wickExplorer osType wick-base os

if [[ "$osType" == ubuntu ]]; then
    serviceName=ssh
fi

wickInfo "Tweaking SSH configuration"
wickHash hashBefore "$config"
sshdTweakSetting "$config" UseDNS use-dns "$@"
sshdTweakSetting "$config" GSSAPIAuthentication gssapi-auth "$@"
sshdTweakSetting "$config" PasswordAuthentication password-auth "$@"
sshdTweakSetting "$config" AllowAgentForwarding agent-forwarding "$@"

if [[ -n "$fasterLogin" ]]; then
    wickSetConfigLine "$config" "GSSAPIAuthentication no"
    wickSetConfigLine "$config" "UseDNS no"
fi

wickHash hashAfter "$config"

if [[ "$hashBefore" != "$hashAfter" ]]; then
    wickStrictRun result wickService is-running "$serviceName"

    if [[ "$result" -eq 0 ]]; then
        wickService reload "$serviceName"
    fi
fi
