#!/usr/bin/env bash
# External: Includes you service into the "network-layer" so
# that it will run after the normal network is up but before
# any of the services that depend on the network being up.
#
# $1 - The name of the service you would like to add.
#
# Examples
#
#     networkLayerInclude tunnel-interface
#
# Returns nothing.
networkLayerInclude() {
    local dependency dependent initType service result

    wickGetArgument service 0 "$@"
    wickExplorer initType wick-base init-system

    dependency=network
    dependent="\$network"

    if [[ systemd == "$initType" ]]; then
        dependency=networking.service
        dependent=network.target
    else
        wickStrictRun result wickService is-enabled virtual-network

        if [[ "$result" -eq 0 ]]; then
            dependency=network
            dependent=virtual-network
        fi
    fi

    wickService add-dependency "$service" "$dependency"
    wickService add-dependency "$dependent" "$service"
}
