#!/usr/bin/env bash
# Installs the Apache 2.x web server and enables named virtual hosts.  Provides
# functions to add virtual hosts and config files.
#
# --start - Start the service as well.  When ommitted, this will ensure the
#           service is not started.
#
# Examples
#
#   wickFormula apache2 --start
#
# Returns nothing.
wickExplorer os wick-base os
wickGetOption start start "$@"

case "$os" in
    centos|redhat)
        wickPackage httpd
        wickService enable httpd
        wickSetConfigLine /etc/httpd/conf/httpd.conf "NameVirtualHost *:80"
        wickService force-state httpd "$start"
        ;;

    *)
        wickPackage apache2
        wickService enable apache2
        wickService force-state httpd "$start"
        ;;
esac
