#!/usr/bin/env bash
# Installs the Apache 2.x web server and enables named virtual hosts.  Provides
# functions to add virtual hosts and config files.
#
# Examples
#
#   wickFormula apache2
#
# Returns nothing.
wickExplorer os wick-base os

case "$os" in
    centos|redhat)
        wickPackage httpd
        wickService enable httpd
        wickService restart httpd
        wickSetConfigLine /etc/httpd/conf/httpd.conf "NameVirtualHost *:80"
        ;;

    *)
        wickPackage apache2
        wickService enable apache2
        wickService restart apache2
        ;;
esac
