#!/usr/bin/env bash

# Install Apache 2 and enable named virtual hosts

wickExplorer OS wick-base os

case "$OS" in
    centos|redhat)
        wickPackage httpd
        wickService enable httpd
        wickService restart httpd
        wick-set-config-line /etc/httpd/conf/httpd.conf "NameVirtualHost *:80"
        ;;

    *)
        wickPackage apache2
        wickService enable apache2
        wickService restart apache2
        ;;
esac
