#!/usr/bin/env bash
# Public: Sets a value in the redis.conf file.  If the config already
# has the configKey provided it will overwrite it.  If the configValue is
# empty, the line which starts with the configKey will be removed.
#
# $1 - The name of the config value you would like to set.
# $2 - The value you would like to set the config value to.
#      If the value is empty it will remove that config setting.
#
# Examples
#
#   redisSetConfigLine "requiresauth" "my password"
#
#   redisSetConfigLine "unsetthisvalue" ""
#
# Returns nothing.
redisSetConfigLine() {
    local configKey configValue

    wickGetArgument configKey 0 "$@"
    wickGetArgument configValue 1 "$@"
    redisConfPath="/etc/redis.conf"

    if [[ -z "$configValue" ]]; then
        wickInfo "Unsetting $configKey in $redisConfPath"
        wickSetConfigLine "$redisConfPath" "" "$configKey"
    else
        wickInfo "Setting a value for $configKey in $redisConfPath"
        wickSetConfigLine "$redisConfPath" "$configKey \"$configValue\""
    fi
}
