#!/usr/bin/env bash

UNAME_M=$(uname -m)
wickDebug "uname -m: $UNAME_M"

case "$UNAME_M" in
    x86_64)
        echo "amd64"
        ;;

    i686*|i386*)
        echo "ia32"
        ;;

    *)
        wickError "Unable to detect architecture"
        echo "UNKNOWN"
        exit 1
        ;;
esac
