#!/usr/bin/env bash
# Determines the architecture that the system is running upon.
#
# Detected values:
#
# * `amd64`
# * `ia32`
#
# Examples
#
#   wickExplorer arch wick-base arch
#
#   if [[ "$arch" != "amd64" ]]; then
#       wickError "Sorry, this requires an AMD64 system."
#       exit 1
#   fi
#
# Returns true when the architecture could be determined.
local unameM

unameM=$(uname -m)
wickDebug "uname -m: $unameM"

case "$unameM" in
    x86_64)
        echo "amd64"
        ;;

    i686*|i386*)
        echo "ia32"
        ;;

    *)
        wickError "Unable to detect architecture from \"$unameM\""
        echo "UNKNOWN"

        exit 1
        ;;
esac
