#!/bin/bash

# Amazon can fail so we try the detection a couple times
for I in {{1..3}}; do
    if getent hosts instance-data | grep -q "169.254.169.254 .*.compute.internal"; then
        wick-debug "Detected Amazon (getent hosts)"
        echo "amazon"
        exit
    fi

    if wick-get-url http://169.254.169.254/latest/meta-data/ami-id > /dev/null; then
        wick-debug "Detected Amazon (url ami-id)"
        echo "amazon"
        exit
    fi
done

wick-debug "Unable to determine machine type"
echo "unknown"
