#!/usr/bin/env bash
# Finds the type of machine we appear to be using.  Attempts to detect
# virtualization environments.  This explorer is a bit rudimentary and could be
# tricked.  Output is written to stdout.
#
# Detected values:
#
# * `amazon`: Running in Amazon AWS
# * `unknown`: All other results
#
# Examples
#
#   wickExplorer result wick-base machine-type
#   if [[ "$result" == "amazon" ]]; then
#       echo "I am in Amazon AWS"
#   fi
if getent hosts instance-data | grep -q "169.254.169.254 .*.compute.internal"; then
    wickDebug "Detected Amazon (getent hosts)"
    echo "amazon"
    exit
fi

# Amazon's network can fail so we try the detection a couple times
for I in {{1..3}}; do
    if wickGetUrl --timeout=1 http://169.254.169.254/latest/meta-data/ami-id > /dev/null; then
        wickDebug "Detected Amazon (url ami-id)"
        echo "amazon"
        exit
    fi
done

# Try to detect if we are in a docker container
if awk -F/ '$2 == "docker"' /proc/self/cgroup | read; then
    echo "docker"
    exit
fi


wickDebug "Unable to determine machine type"
echo "unknown"
