#!/usr/bin/env bash
# Makes an educated guess to determine the OS that is running.  Writes the
# OS to stdout for `wickExplorer`.
#
# Detected values:
#
# * `apple`: Mac OS X
# * `centos`: CentOS
# * `redhat`: RedHat
# * `ubuntu`: Ubuntu
#
# Examples
#
#   wickExplorer RESULT wick-base os
#   case "$RESULT" in
#       apple)
#           brew install packageName
#           ;;
#
#       redhat)
#           yum install packageName
#           ;;
#
#       ubuntu)
#           apt-get install packageName
#           ;;
#   esac
#
# Returns 0 on success or 1 when the OS can't be determined.

# On RedHat-like systems you can see if there's a package called
# `centos-release`.  If so, you are on CentOS.
#
# Examples
#
#   if isReallyCentos; then
#       echo "This is CentOS, not RedHat"
#   fi
#
# Returns true if this is CentOS.
isReallyCentos() {
    rpm -q centos-release > /dev/null 2>&1
}

# Determines if this is truly RedHat or a derivative.  Writes the OS to stdout.
#
# Examples
#
#   detectRealRedhat
#
# Returns nothing.
detectRealRedhat() {
    if isReallyCentos; then
        echo "centos"
    else
        echo "redhat"
    fi
}

if [[ -f /etc/arch-release ]]; then
    echo "arch"
    exit
fi

if wickCommandExists lsb_release; then
    distributor=$(lsb_release -s -i 2>&1)
    wickDebug "Distributor: $distributor"

    case "$distributor" in
        RedHatEnterprise*)
            detectRealRedhat
            exit
            ;;

        Ubuntu)
            echo "ubuntu"
            exit
            ;;
    esac
fi

wickDebug "MACHTYPE=$MACHTYPE"

if [[ "$MACHTYPE" == *"-redhat-"* ]]; then
    detectRealRedhat
    exit
fi

if [[ "$MACHTYPE" == *"-apple-"* ]]; then
    echo "osx"
    exit
fi

if wickCommandExists uname; then
    unameV=$(uname -v 2>&1)
    wickDebug "unameV=$unameV"

    if [[ "$unameV" == *"Ubuntu"* ]]; then
        echo "ubuntu"
        exit
    fi
fi

wickError "Unable to detect OS"
echo "UNKNOWN"
exit 1
