#!/usr/bin/env bash
# Attempts to find the release version of the distribution that is running.
#
# Example:
#
#   wickExplorer
#
# Returns true on success.
declare os

wickExplorer os wick-base os || :

case "$os" in
    arch)
        date --utc --iso-8601=minutes -d "$(date --iso-8601=minutes
            -d "$(grep '\[PACMAN\] synchronizing package lists' /var/log/pacman.log | \
            tail -1 | cut -b 2-17)")" || exit $?
        ;;

    centos)
        rpm -q centos-release | cut -d - -f 3- | cut -d . -f 1 | tr - . || exit $?
        ;;

    osx)
        echo "Unsupported OS: $os"

        exit 1
        ;;

    redhat)
        rpm -q redhat-release | cut -d - -f 3- | cut -d . -f 1 | tr - . || exit $?
        ;;

    ubuntu)
        if wickCommandExists lsb_release; then
            lsb_release -a | grep ^Release: | sed 's/.*:\s*//' || exit $?
        elif [[ -f "/etc/lsb-release" ]]; then
            grep 'DISTRIB_RELEASE=' /etc/lsb-release | cut -d'=' -f2 || exit $?
        else
            wickDebug 'Unable to find command "lsb_release" or file "/etc/lsb-release"' || exit $?

            exit 1
        fi

        ;;

    UNKNOWN)
        echo "UNKNOWN"
        ;;

    *)
        echo "Unknown OS: $os"

        exit 1
        ;;
esac
