#!/usr/bin/env bash
# Attempts to find the release version of the distribution that is running.
#
# Example:
#
#   wickExplorer
#
# Returns true on success.
wickExplorer os wick-base os || true

case "$os" in
    arch)
        date --utc --iso-8601=minutes -d "$(date --iso-8601=minutes
            -d "$(grep '\[PACMAN\] synchronizing package lists' /var/log/pacman.log | \
            tail -1 | cut -b 2-17)")"
        ;;

    centos)
        rpm -q centos-release | cut -d - -f 3- | cut -d . -f 1 | tr - .
        ;;

    osx)
        echo "Unsupported OS: $os"
        exit 1
        ;;

    redhat)
        rpm -q redhat-release | cut -d - -f 3- | cut -d . -f 1 | tr - .
        ;;

    ubuntu)
        lsb_release -a | grep 'Release:' | sed 's/Release:\s*//g'
        ;;

    UNKNOWN)
        echo "UNKNOWN"
        ;;

    *)
        echo "Unknown OS: $os"
        exit 1
        ;;
esac
