#!/usr/bin/env bash

cat <<EOF
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9001 qdisc pfifo_fast state UP qlen 1000
    link/ether 06:0f:6f:ab:a8:cb brd ff:ff:ff:ff:ff:ff
    inet 192.168.70.238/20 brd 192.168.79.255 scope global eth0
    inet6 fe80::40f:6fff:feab:a8cb/64 scope link
       valid_lft forever preferred_lft forever
EOF
