#!/usr/bin/env bash
# Installs dnsmasq and adds it as a nameserver.
#
# Examples
#
#   wickFormula dnsmasq
#
# Returns nothing
wickPackage dnsmasq
wickMakeDir /etc/dnsmasq.d/
wickSetConfigLine /etc/dnsmasq.conf "conf-dir=/etc/dnsmasq.d"
wickService restart dnsmasq
wickService enable dnsmasq

# Insert dnsmasq into the resolver
wickSetConfigLine /etc/dhcp/dhclient.conf "prepend domain-name-servers 127.0.0.1;" "prepend domain-name-servers"

if grep -q ^nameserver /etc/resolv.conf; then
    sed --follow-symlinks -i '/^nameserver/inameserver 127.0.0.1' /etc/resolv.conf
else
    echo "nameserver 127.0.0.1" >> /etc/resolv.conf
fi
