#!/usr/bin/env bash
# Installs dnsmasq and adds it as a nameserver.
#
# --start       - Starts the service. If not specified, the service will not be
#                 running when the formula finishes.
#
# --protect-dns - Adds the contents of [protect-dns-resolver-config](files/protect-dns-resolver-config)
#                 to `/etc/dhcp/dhclient-enter-hooks` which prevents
#                 `resolv.conf` from being corrupt by `make_resolv_conf`. One
#                 situation where this occurs is if there is insufficient
#                 disc space remaining to write a new `resolv.conf`.
#                 This is only a problem if there is a service running as root
#                 and can access and ultimately fill the system reserved
#                 portion of disc space.
#
# When `--start` is used, `/etc/resolv.conf` is updated to use dnsmasq.
# Without `--start`, the nameserver entry is not added.  It would be assumed
# that either the machine will be rebooted (and thus dnsmasq's nameserver
# entry would be added with the dhclient hook) or `/etc/resolv.conf` will
# be updated at a later time when dnsmasq is enabled.
#
# Examples
#
#   # Installs dnsmasq.
#   wickFormula dnsmasq
#
#   # Installs dnsmasq and starts it immediately.
#   wickFormula dnsmasq --start
#
#   # Installs dnsmasq and prevents the corruption of resolv.conf.
#   wickFormula dnsmasq --protect-dns
#
# Returns nothing.
declare os osVersion start protectDns

wickGetOption start --start "$@"
wickGetOption protectDns --protect-dns "$@"

# In Ubuntu dnsmasq uses resolvconf to enable dnsmasq after starting the service
# if it is installed. In newer versions of Ubuntu it doesn't install resolvconf
# and as a result dnsmasq is installed and started but not used.
wickExplorer os wick-base os
wickExplorer osVersion wick-base os-version

if [[ "$os" == "ubuntu" && "${osVersion:0:2}" -gt "16" ]]; then
    wickPackage resolvconf
fi

wickPackage dnsmasq
wickMakeDir /etc/dnsmasq.d/
wickSetConfigLine /etc/dnsmasq.conf "conf-dir=/etc/dnsmasq.d"
wickService enable dnsmasq
wickService force-state dnsmasq "$start"

# Insert dnsmasq into the resolver
#
# The normal, one-line method may not work in all situations.
# http://www.fidian.com/problems-only-tyler-has/dhclient-not-honoring-prepend-config
# wickSetConfigLine /etc/dhcp/dhclient.conf "prepend domain-name-servers 127.0.0.1;" "prepend domain-name-servers"
if [[ ! -f /etc/dhcp/dhclient-enter-hooks ]]; then
    echo "#!/bin/sh" > /etc/dhcp/dhclient-enter-hooks
    chmod 755 /etc/dhcp/dhclient-enter-hooks
fi

wickMakeFile dnsmasq - | wickAddConfigSection /etc/dhcp/dhclient-enter-hooks dnsmasq

# When --protect-dns is used, enable protect-dns-resolver-config.
if [[ -n "$protectDns" ]]; then
    wickMakeFile protect-dns-resolver-config - | wickAddConfigSection /etc/dhcp/dhclient-enter-hooks protect-dns-resolver-config
fi

# When --start is used, enable dnsmasq.
if [[ -n "$start" ]]; then
    RESOLV=$(
        grep -v ^nameserver /etc/resolv.conf || :
        echo "nameserver 127.0.0.1"
        grep ^nameserver /etc/resolv.conf | grep -v "^nameserver[ \t][ \t]*127\\." || :
    )
    echo "$RESOLV" > /etc/resolv.conf
fi
