#!/bin/bash

formula-template() {
    local ENGINE
    
    ENGINE=${1##*.}
    "formula-template-$ENGINE" "$WICK_FORMULA_DIR/templates/$SRC"
}

formula-template-sh() {
    (
        /bin/sh "$1"
    )
}

formula-template-bash() {
    (
        . "$1"
    )
}

