#!/bin/bash

install-formula-file() {
    local ARGS_mode ARGS_owner ARGS_template DEST SRC UNPARSED
    
    ARGS_mode=""
    ARGS_owner=""
    ARGS_template=""
    wick-parse-arguments UNPARSED "${1+"$@"}"
    SRC="$WICK_FORMULA_DIR/files/${UNPARSED[0]}"
    DEST="${UNPARSED[1]}"

    if [ -z "$DEST" ]; then
        wick-debug "Writing file to stdout: $SRC"

        if [[ -z "$ARGS_template" ]]; then
            cat "$SRC"
        else
            formula-template "$SRC"
        fi
    else
        wick-debug "Copying $SRC to $DEST"

        if [ -d "$DEST" ]; then
            DEST="$DEST/${UNPARSED[0]}"
        fi

        if [[ -z "$ARGS_template" ]]; then
            cp "$SRC" "$DEST"
        else
            formula-template "$SRC" > "$DEST"
        fi

        if [ ! -z "$ARGS_owner" ]; then
            wick-debug "Changing ownership: $ARGS_owner"
            chown "$ARGS_owner" "$DEST"
        fi

        if [ ! -z "$ARGS_mode" ]; then
            wick-debug "Changing mode: $ARGS_mode"
            chmod "$ARGS_mode" "$DEST"
        fi
    fi
}
