#!/usr/bin/env bash

wickServiceAddDependencyIfExists() {
    local service dependency

    wickGetArgument service 0 "$@"
    wickGetArgument dependency 1 "$@"

    if wickServiceIsEnabled "$dependency"; then
        wickServiceAddDependency "$service" "$dependency"
    else
        wickInfo "Service $dependency does not exist.  No adding it as a dependency"
    fi
}
