#!/usr/bin/env bash
# Internal: Stops a service.
#
# $1 - Service name to stop.
#
# Examples
#
#   wickServiceStop rsync
#
# Returns nothing.
wickServiceStop() {
    local service serviceCommandExists initType

    wickGetArgument service 0 "$@"
    wickExplorer initType wick-base init-system

    wickStrictRun serviceCommandExists wickCommandExists service

    wickInfo "Stopping service: $service"

    if [[ "$initType" == systemd ]]; then
        nohup systemctl stop "$service"
    elif [[ "$serviceCommandExists" -eq 0 ]]; then
        nohup service "$service" stop
    else
        nohup "/etc/init.d/$service" stop
    fi
}
