#!/usr/bin/env bash
# Internal: Enables a service so it starts at boot.
#
# $1 - Service name.
#
# Examples
#
#   wickServiceEnable mongod
#
# Returns nothing.
wickServiceEnable() {
    local initType service

    wickGetArgument service 0 "$@" || return $?
    wickInfo "Enabling service: $service" || return $?

    wickExplorer initType wick-base init-system || return $?

    if [[ "$initType" == systemd ]]; then
        systemctl enable "$service" || return $?
    else
        chkconfig "$service" on || return $?
    fi
}
