#!/usr/bin/env bash
# Internal: Figures out if a service exists and is enabled.
# Enabled means it will start on boot.
#
# $1 - Service name.
#
# Examples:
#     wickServiceIsEnabled mysql
#
# Returns true if it finds the service and it is enabled.
wickServiceIsEnabled() {
    local initType service

    wickGetArgument service 0 "$@"
    wickExplorer initType wick-base init-system

    if [[ systemd == "$initType" ]]; then
        systemctl is-enabled "$service"
    else
        wickServiceIsEnabledSysv
    fi
}
