#!/usr/bin/env bash
# Internal: Determines if a service is running
#
# $1 - Service name to check.
#
# Examples
#
#   wickServiceIsRunning ssh
#
# Returns nothing.
wickServiceIsRunning() {
    local initType service

    wickGetArgument service 0 "$@" || return $?
    wickExplorer initType wick-base init-system || return $?
    wickInfo "Checking if service is running: $service" || return $?

    if [[ "$initType" == systemd ]]; then
        systemctl status "$service" || return $?
    elif wickCommandExists service; then
        service "$service" status || return $?
    else
        "/etc/init.d/$service status" || return $?
    fi
}
