#!/usr/bin/env bash
# Internal: Handles adding a dependency specifically if we are
# running systemd.
#
# $1 - The name of the service you wish to add a dependency to.
# $2 - The name of the service you wish to add as a dependency to the service.
#
# Examples
#
#   wickServiceAddDependencySystemd mysql virtual-network
#
# Returns nothing.
wickServiceAddDependencySystemd() {
    local dependency overridePath paths service

    wickServiceGetNameArgumentSystemd service 0 "$@" || return $?
    wickServiceGetNameArgumentSystemd dependency 1 "$@" || return $?

    wickServiceOverridePathSystemd paths "$service" || return $?
    wickArrayJoin overridePath "/" "${paths[@]}" || return $?

    wickDebug "Adding \"$dependency\" as a dependency of \"$service\"" || return $?

    # Add a Wants= after the [Unit] section
    sed -i 's/^\[\Unit\]/&\nWants='"$dependency"'\nAfter='"$dependency"'/' "$overridePath" || return $?

    # To pick up changes
    wickServiceOverride "$service" || return $?
}
