#!/usr/bin/env bash
# Internal: Stops a service.
#
# $1 - Service name to stop.
#
# Examples
#
#   wickServiceStop rsync
#
# Returns nothing.
wickServiceStop() {
    local service initType

    wickGetArgument service 0 "$@"
    wickExplorer initType wick-base init-system

    wickInfo "Stopping service: $service"

    if [[ "$initType" == systemd ]]; then
        nohup systemctl stop "$service"
    else
        nohup service "$service" stop
    fi
}
