#!/usr/bin/env bash
# Internal: Disable a service so it doesn't start on boot.
#
# $1 - Service name.
#
# Examples
#
#   wickServiceDisable consul
#
# Returns nothing.
wickServiceDisable() {
    local service initType

    wickGetArgument service 0 "$@"
    wickInfo "Disabling service: $service"

    wickExplorer initType wick-base init-system

    if [[ "$initType" == systemd ]]; then
        systemctl disable "$service"
    else
        chkconfig "$service" off
    fi
}
