#!/usr/bin/env bash
# Internal: Checks only for sysv style services which
# include files in /etc/init.d/
#
# $1 - The name of the service to check.
#
# Returns true if the service is found and is enabled.
wickServiceIsEnabledSysv() {
    local service result
    wickGetArgument service 0 "$@"

    result=$(chkconfig --list | grep "$service")

    if [[ -n "$result" ]]; then
        # after removing the service name the only thing that will
        # be left is <runLevel>:<on|off>.  I look for it to be enabled
        # at any run level.
        if echo "$result" | sed 's/'"$service"'\s*//' | grep -q on; then
            return 0
        fi
    fi

    return 1

}
