#!/bin/bash

wick-service() {
    local ARGS_force UNPARSED

    ARGS_force=""
    wick-parse-arguments UNPARSED "$@"
    ACTION="$UNPARSED[0]"
    UNPARSED=("${UNPARSED[@]:1}")

    case "$ACTION" in
        add)
            wick-service-add "${UNPARSED[@]}"
            ;;

        disable)
            wick-service-disable "${UNPARSED[@]}"
            ;;

        enable)
            wick-service-enable "${UNPARSED[@]}"
            ;;

        make-override)
            wick-service-make-override "${UNPARSED[@]}"
            ;;

        override)
            wick-service-override "${UNPARSED[@]}"
            ;;

        reload)
            wick-service-reload "${UNPARSED[@]}"
            ;;

        restart)
            wick-service-restart "${UNPARSED[@]}"
            ;;

        start)
            wick-service-start "${UNPARSED[@]}"
            ;;

        stop)
            wick-service-stop "${UNPARSED[@]}"
            ;;

        *)
            wick-error "Unknown service command: $ACTION"
            wick-error "Must be one of: add, disable, enable, make-override, override, reload, restart, start, stop"
            ;;
    esac
}


wick-service-add() {
    wick-info "Adding service: $1"

    if [[ ! -f "/etc/init.d/$1" ]] || [[ ! -z "$ARGS_force" ]]; then
        install-formula-file --mode=0755 --owner=root:root "$2" /etc/init.d/"$1"
        chkconfig --add "$1"
    else
        wick-info "Service already exists and --force flag was not specified"
    fi
}

wick-service-disable() {
    wick-info "Disabling service: $1"
    chkconfig "$1" off
}

wick-service-enable() {
    wick-info "Enabling service: $1"
    chkconfig "$1" on
}

wick-service-make-override() {
    local DEST LABEL LSB SERVICE SRC VALUE

    SERVICE="$1"
    SRC="/etc/init.d/$SERVICE"
    DEST="/etc/chkconfig.d/$SERVICE"
    wick-info "Making override for service: $SERVICE"

    if [[ -f "$DEST" ]] && [[ -z "$ARGS_force" ]]; then
        return 0
    fi

    if [[ ! -f "$SRC" ]]; then
        echo "Source service file does not exist: $SRC" >&2
        return 1
    fi

    LSB=$(sed '0,/^### BEGIN INIT INFO/ d; /^### END INIT INFO/,$ d' "$SRC")
    grep '^# chkconfig:' "$SRC" | head -n 1 > "$DEST"
    echo '### BEGIN INIT INFO' >> "$DEST"

    for LABEL in Provides Default-Start Default-Stop Required-Start Required-Stop Should-Start Should-Stop; do
        VALUE=$(echo "$LSB" | grep '^# '"$LABEL"':' || echo "")
        echo "${VALUE:-# ${LABEL}:}" >> "$DEST"
    done

    echo '### END INIT INFO' >> "$DEST"
    wick-service-override "$SERVICE"
}

wick-service-override() {
    wick-info "Updating scripts with override for service: $1"
    chkconfig --override "$1"
}

wick-service-reload() {
    wick-info "Reloading service: $1"
    nohup service "$1" reload
}

wick-service-restart() {
    wick-info "Restarting service: $1"
    nohup service "$1" restart
}

wick-service-start() {
    wick-info "Starting service: $1"
    nohup service "$1" start
}

wick-service-stop() {
    wick-info "Stopping service: $1"
    nohup service "$1" stop
}

