#!/bin/bash

wick-set-config-line() {
    local KEY TEMPFILE

    KEY=${2/ *}
    KEY=${KEY/=*}
    temp-directory TEMP
    TEMPFILE="$TEMP/add-line"
    cat "$1" | grep -v "^$KEY" > "$TEMPFILE"
    echo "$2" >> "$TEMPFILE"
    
    # Avoid using cp as this preserves file ownership and permissions
    cat "$TEMPFILE" > "$1"
}
