#!/usr/bin/env bash

wickServiceGetNameArgumentSystemd() {
    local index target name

    wickGetArgument target 0 "$@" || return $?
    wickGetArgument index 1 "$@" || return $?

    shift 2

    wickGetArgument name "$index" "$@" || return $?

    if [[ "$name" != *.target && "$name" != *.timer && "$name" != *.service ]]; then
        name="$name.service"
    fi

    local "$target" && wickIndirect "$target" "$name"
}
