#!/usr/bin/env bash
# Internal: Determines if a service is running
#
# $1 - Service name to check.
#
# Examples
#
#   wickServiceIsRunning ssh
#
# Returns nothing.
wickServiceIsRunning() {
    local service initType

    wickGetArgument service 0 "$@"
    wickExplorer initType wick-base init-system

    wickInfo "Checking if service is running: $service"

    if [[ "$initType" == systemd ]]; then
        systemctl status "$service"
    else
        service "$service" status
    fi
}
