#!/bin/bash
# Internal: Makes the service provided depend on another service
# which could change the order services are loaded in at boot time.
#
# $1 - The name of the service you wish to add a dependency to.
# $2 - The name of the service you wish to add as a dependency to the service.
#
# Returns: 1 if $1 is not provided and 2 if $2 is not provided.
wickServiceAddDependency() {
    local dependency initType service

    wickExplorer initType wick-base init-system
    wickGetArgument service 0 "$@"
    wickGetArgument dependency 1 "$@"

    if [[ -z "$service" ]]; then
        wickError "wickServiceAddDependency requires a service to be provided as the first argument"
        return 1
    fi

    if [[ -z "$dependency" ]]; then
        wickError "wickServiceAddDependency requires a dependency to be provided as the second argument"
        return 2
    fi

    wickServiceMakeOverride "$@"

    if [[ systemd == "$initType" ]]; then
        wickServiceAddDependencySystemd "$@"
    else
        wickServiceAddDependencyUpstart "$@"
    fi
}
