#!/usr/bin/env bash
# Internal: Starts a service.
#
# $1 - Service name to start.
#
# Examples
#
#   wickServiceStart cron
#
# Returns nothing.
wickServiceStart() {
    local service initType

    wickGetArgument service 0 "$@"
    wickExplorer initType wick-base init-system

    wickInfo "Starting service: $service"

    if [[ "$initType" == systemd ]]; then
        nohup systemctl start "$service"
    else
        nohup service "$service" start
    fi
}
