#!/usr/bin/env bash
# Internal: Starts a service.
#
# $1 - Service name to start.
#
# Examples
#
#   wickServiceStart cron
#
# Returns nothing.
wickServiceStart() {
    local service serviceCommandExists initType

    wickGetArgument service 0 "$@"
    wickExplorer initType wick-base init-system

    wickStrictRun serviceCommandExists wickCommandExists service

    wickInfo "Starting service: $service"

    if [[ "$initType" == systemd ]]; then
        nohup systemctl start "$service"
    elif [[ "$serviceCommandExists" -eq 0 ]]; then
        nohup service "$service" start
    else
        nohup "/etc/init.d/$service" start
    fi
}
