#!/usr/bin/env bash
# Internal: Helper function to take action on apt-based systems.
#
# $1 - Desired package state.  One of "clean", "install", "uninstall" or
#      "exists".
# $2 - Package name, required if state is not "clean".
#
# Examples
#
#   wickPackageApt install apache2
#
# Return true on success.
wickPackageApt() {
    local state

    state=$1
    shift

    case "$state" in
        clean)
            wickWaitFor 600 wickIsAptAvailable || return $?
            apt-get clean || return $?
            ;;

        exists)
            if apt-cache show "$@" > /dev/null 2>&1; then
                wickDebug "Package exists: $*" || return $?

                return 0
            fi

            wickDebug "Package does not exist: $*" || return $?

            return 1
            ;;

        install)
            wickWaitFor 600 wickIsAptAvailable || return $?
            apt-get install -y "$@" || return $?
            ;;

        uninstall)
            wickWaitFor 600 wickIsAptAvailable || return $?
            apt-get purge -y "$@" || return $?
            ;;

        *)
            echo "Unknown package state: $state"

            return 1
    esac
}
