#!/usr/bin/env bash
# Internal: Restarts a service.
#
# $1 - Service name to restart.
#
# Examples
#
#   wickServiceRestart tinyproxy
#
# Returns nothing.
wickServiceRestart() {
    local service initType

    wickGetArgument service 0 "$@"
    wickExplorer initType wick-base init-system

    wickInfo "Restarting service: $service"

    if [[ "$initType" == systemd ]]; then
        nohup systemctl restart "$service"
    else
        nohup service "$service" restart
    fi
}
