#!/bin/bash

wick-make-user() {
    local ARGS PASSWD UNPARSED USERHOME USERNAME

    ARGS_daemon=""
    ARGS_home=""
    ARGS_move_home=""
    ARGS_name=""
    ARGS_no_skel=""
    ARGS_shell=""
    ARGS_system=""
    wick-parse-arguments UNPARSED "$@"
    USERNAME=${UNPARSED[0]}

    if [[ -z "$USERNAME" ]]; then
        wick-error "You must specify a username for wick-make-user"
        return 1
    fi

    # Set reasonable defaults for daemons
    if [[ ! -z "$ARGS_daemon" ]]; then
        ARGS_move_home=""
        ARGS_no_skel=true
        ARGS_shell=/bin/false
        ARGS_system=true
    fi

    PASSWD=$(getent passwd "$USERNAME" || true)

    if [[ -z "$PASSWD" ]]; then
        wick-info "Creating user: $USERNAME"
        ARGS=(useradd)

        if [[ ! -z "$ARGS_home" ]]; then
            ARGS=("${ARGS[@]}" "-d" "$ARGS_home")
        fi

        if [[ ! -z "$ARGS_name" ]]; then
            ARGS=("${ARGS[@]}" "-c" "$ARGS_name")
        fi

        if [[ ! -z "$ARGS_no_skel" ]]; then
            ARGS=("${ARGS[@]}" "-M")
        fi

        if [[ ! -z "$ARGS_shell" ]]; then
            ARGS=("${ARGS[@]}" "-s" "$ARGS_shell")
        fi

        if [[ ! -z "$ARGS_system" ]]; then
            ARGS=("${ARGS[@]}" "-r")
        fi

        ARGS=("${ARGS[@]}" "$USERNAME")
        wick-debug "Command: ${ARGS[@]}"
        "${ARGS[@]}"
    else
        wick-info "Altering user: $USERNAME"
        ARGS=(usermod)

        if [[ ! -z "$ARGS_home" ]]; then
            ARGS=("${ARGS[@]}" "-d" "$ARGS_home")
        fi

        if [[ ! -z "$ARGS_move_home" ]]; then
            ARGS=("${ARGS[@]}" "-m")
        fi

        if [[ ! -z "$ARGS_name" ]]; then
            ARGS=("${ARGS[@]}" "-c" "$ARGS_name")
        fi

        if [[ ! -z "$ARGS_shell" ]]; then
            ARGS=("${ARGS[@]}" "-s" "$ARGS_shell")
        fi

        ARGS=("${ARGS[@]}" "$USERNAME")
        wick-debug "Command: ${ARGS[@]}"
        "${ARGS[@]}"
    fi

    USERHOME=$(getent passwd "$USERNAME" | cut -d : -f 6)
    wick-make-dir --owner="$USERNAME:$USERNAME" --mode=0755 "$USERHOME"
}
