#!/usr/bin/env bash
# Internal: Restarts a service if it is running.
#
# $1 - Service name to possibly restart.
#
# Examples
#
#   wickServiceConditionalRestart tinyproxy
#
# Returns nothing.
wickServiceConditionalRestart() {
    local result service

    wickGetArgument service 0 "$@"
    wickStrictRun result wickService is-running "$service"

    if [[ "$result" -eq 0 ]]; then
        wickService restart "$service"
    fi
}
