#!/usr/bin/env bash
# Internal: Helper function to take action on apt-based systems.
#
# $1 - Desired package state.  One of "clean", "install", "uninstall" or
#      "exists".
# $2 - Package name, required if state is not "clean".
#
# Examples
#
#   wickPackageApt install apache2
#
# Return true on success.
wickPackageApt() {
    local loop state

    state=$1
    shift

    case "$state" in
        clean)
            for loop in {1..3}; do
                wickInfo "Cleaning (try $loop of 3)"
                wickWaitFor 600 wickIsAptAvailable || return $?
                apt-get clean && return 0
            done

            wickError "Could not run apt-get clean"

            return 1
            ;;

        exists)
            if apt-cache show "$@" > /dev/null 2>&1; then
                wickDebug "Package exists: $*" || return $?

                return 0
            fi

            wickDebug "Package does not exist: $*" || return $?

            return 1
            ;;

        install)
            for loop in {1..3}; do
                wickInfo "Installing (try $loop of 3)"
                wickWaitFor 600 wickIsAptAvailable || return $?
                apt-get install -y "$@" && return 0
            done

            wickError "Could not install package"

            return 1
            ;;

        uninstall)
            for loop in {1..3}; do
                wickInfo "Uninstalling (try $loop of 3)"
                wickWaitFor 600 wickIsAptAvailable || return $?
                apt-get purge -y "$@" && return 0
            done

            wickError "Could not uninstall package"

            return 1
            ;;

        *)
            echo "Unknown package state: $state"

            return 1
    esac
}
