#!/bin/bash

wick-make-dir() {
    local DEST MODE OWNER

    wick-get-option MODE mode "$@"
    wick-get-option OWNER owner "$@"
    wick-get-argument DEST 0 "$@"
    wick-debug "Making directory: $DEST"
    mkdir -p "$DEST"

    if [ ! -z "$OWNER" ]; then
        wick-debug "Changing ownership: $OWNER"
        chown "$OWNER" "$DEST"
    fi

    if [ ! -z "$MODE" ]; then
        wick-debug "Changing mode: $MODE"
        chmod "$MODE" "$DEST"
    fi
}
