#!/usr/bin/env bash
# Internal: Restarts a service.
#
# $1 - Service name to restart.
#
# Examples
#
#   wickServiceRestart tinyproxy
#
# Returns nothing.
wickServiceRestart() {
    local initType service

    wickGetArgument service 0 "$@" || return $?
    wickExplorer initType wick-base init-system || return $?
    wickInfo "Restarting service: $service" || return $?

    if [[ "$initType" == systemd ]]; then
        nohup systemctl restart "$service" || return $?
    elif wickCommandExists service; then
        nohup service "$service" restart || return $?
    else
        nohup "/etc/init.d/$service" restart || return $?
    fi
}
