#!/usr/bin/env bash
# Internal: Determines if a service is running
#
# $1 - Service name to check.
#
# Examples
#
#   wickServiceIsRunning ssh
#
# Returns nothing.
wickServiceIsRunning() {
    local initType service serviceCommandExists

    wickGetArgument service 0 "$@"
    wickExplorer initType wick-base init-system

    wickInfo "Checking if service is running: $service"

    wickStrictRun serviceCommandExists wickCommandExists service

    if [[ "$initType" == systemd ]]; then
        systemctl status "$service"
    elif [[ "$serviceCommandExists" -eq 0 ]]; then
        service "$service" status
    else
        "/etc/init.d/$service status"
    fi
}
