#!/bin/bash

wick-package() {
    local ARGS_uninstall OS STATE

    STATE="install"
    ARGS_uninstall=""
    wick-parse-arguments UNPARSED "$@"

    if [[ ! -z "$ARGS_uninstall" ]]; then
        STATE="uninstall"
    fi

    wick-explorer OS wick-base os

    case "$OS" in
        centos|redhat)
            wick-package-yum "$STATE" "${UNPARSED[@]}" && return 0
            ;;

        ubuntu|debian)
            wick-package-apt "$STATE" "${UNPARSED[@]}" && return 0
            ;;

        *)
            wick-error "Unable to determine package manager"
            return 1
            ;;
    esac
}

wick-package-yum() {
    local ARGS STATE

    ARGS=()
    STATE=$1
    shift

    case "$STATE" in
        install)
            if [[ ! -z "$YUM_ENABLE_REPO" ]]; then
                ARGS=("${ARGS[@]}" "--enablerepo=$YUM_ENABLE_REPO")
            fi

            yum "${ARGS[@]}" install -y "$@"
            ;;

        uninstall)
            yum remove -y "$@"
            ;;

        *)
            echo "Unknown package state: $STATE"
            return 1
    esac
}

wick-package-apt() {
    local STATE

    STATE=$1
    shift

    case "$STATE" in
        install)
            apt-get install -y "$@"
            ;;

        uninstall)
            apt-get purge -y "$@"
            ;;

        *)
            echo "Unknown package state: $STATE"
            return 1
    esac
}
