#!/usr/bin/env bash
# Create a group on the system.
#
# $1 - Group name to create.
#
# The group will be created if it does not already exist.
#
# Examples
#
#   # Create a group for a Tomcat server
#   wickMakeGroup tomcat
#
# Returns 0 on success, 1 if the required arguments are not passed in.
wickMakeGroup() {
    local args groupInfo groupName

    wickGetArgument groupName 0 "$@" || return $?

    if [[ -z "$groupName" ]]; then
        wickError "You must specify a group name for wickMakeGroup." || return $?

        return 1
    fi

    groupInfo=$(getent group "$groupName" || :)

    if [[ -z "$groupInfo" ]]; then
        wickInfo "Creating group: $groupName" || return $?
        groupadd "$groupName" || return $?
    fi
}
