#!/usr/bin/env bash
# Public: Control services.  Add services, enable and disable them at boot up.
# Start, stop, reload, restart services.  Helps with the creation of override
# files (for `chkconfig`).
#
# $1 - Action to perform, detailed below.
# $2 - Service name.
#
# Examples
#
#   # Creating a new service using the formula's files/consul.init
#   # and copying it to the right spot.
#   wickService add consul consul.init
#   wickService enable consul
#   wickService start consul
#
#   # Make Apache require Consul before starting
#   wickService add-dependency apache2 consul
#
# Returns nothing.
#
#
# ### `add [--force] [--*] SERVICE FORMULA_FILE`
#
# Use `wickMakeFile` to copy the formula file to `/etc/init.d/` for the named
# service.  Does not enable nor start the service.  Does not add the service if
# the file already exists unless `--force` is also used.  You can also use any
# additional options that `wickMakeFile` supports.
#
# ### `add-dependency <service> <dependency>`
#
# Makes the service provided depend on the service passed as the dependency.
#
#
# ### `add-dependency-if-enabled` <service> <dependency>
#
# Only adds the dependency if that dependency exists as a service and is enabled
# to start at boot time.
#
#
# ### `disable SERVICE`
#
# Disable the service from starting at boot.  Does not stop the service if it
# is already running.
#
#
# ### `enable SERVICE`
#
# Enable the service at boot.  Does not start the service.
#
#
# ### `force-state SERVICE STATE`
#
# Used by other scripts to force the service to be running or stopped.
#
# SERVICE - Name of service to manage.
# STATE - If empty, the service is stopped.  If not empty the service is
#         restarted (ensuring it is running properly).
#
# ### `is-enabled` SERVICE
#
# Checks to see if a service both exists and is enabled so that it will
# start on boot.  If any runlevel is enabled this will return true.
#
#
# ### `make-override [--force] SERVICE`
#
# Creates `/etc/chkconfig.d/SERVICE` that is used by `chkconfig` to help
# determine order.  This override file can be modified to list additional
# dependencies to influence the boot order of scripts.  Make sure to call
# `wickService override` when you update an override file.  When using
# `--force`, this will overwrite any override file that may already exist.
#
#
#
# ### `override SERVICE`
#
# Calls `chkconfig override` to apply any changes made to override files.
#
#
# ### `reload SERVICE`
#
# Reloads the given service.
#
#
# ### `restart SERVICE`
#
# Stops and starts the given service.
#
#
# ### `start SERVICE`
#
# Starts the service.
#
#
# ### `stop SERVICE`
#
# Stops the service.
#
wickService() {
    local action options unparsed

    wickGetOptions options "$@" || return $?
    wickGetArgument action 0 "$@" || return $?
    wickGetArguments unparsed "$@" || return $?

    if [[ ${#unparsed[@]} -lt 1 ]]; then
        wickError "Specify action to take and the service name to act upon." || return $?

        return 1
    fi

    if [[ ${#unparsed[@]} -lt 2 ]]; then
        wickError "Must specify service name to act upon" || return $?

        return 1
    fi

    # Remove the action from the unparsed items. The IFS setting is required
    # for this to work in bash 3 regardless to the IFS setting.
    # See https://github.com/fidian/gg-core/pull/7
    IFS= unparsed=("${unparsed[@]:1}")

    case "$action" in
        add)
            wickServiceAdd "${unparsed[@]}" "${options[@]-}" || return $?
            ;;

        add-dependency)
            wickServiceAddDependency "${unparsed[@]}" "${options[@]-}" || return $?
            ;;

        add-dependency-if-enabled)
            wickServiceAddDependencyIfEnabled "${unparsed[@]}" "${options[@]-}" || return $?
            ;;

        conditional-restart)
            wickServiceConditionalRestart "${unparsed[@]}" "${options[@]-}" || return $?
            ;;

        disable)
            wickServiceDisable "${unparsed[@]}" "${options[@]-}" || return $?
            ;;

        enable)
            wickServiceEnable "${unparsed[@]}" "${options[@]-}" || return $?
            ;;

        force-state)
            wickServiceForceState "${unparsed[@]}" "${options[@]-}" || return $?
            ;;

        is-enabled)
            wickServiceIsEnabled "${unparsed[@]}" "${options[@]-}" || return $?
            ;;

        is-running)
            wickServiceIsRunning "${unparsed[@]}" "${options[@]-}" || return $?
            ;;

        make-override)
            wickServiceMakeOverride "${unparsed[@]}" "${options[@]-}" || return $?
            ;;

        override)
            wickServiceOverride "${unparsed[@]}" "${options[@]-}" || return $?
            ;;

        reload)
            wickServiceReload "${unparsed[@]}" "${options[@]-}" || return $?
            ;;

        restart)
            wickServiceRestart "${unparsed[@]}" "${options[@]-}" || return $?
            ;;

        start)
            wickServiceStart "${unparsed[@]}" "${options[@]-}" || return $?
            ;;

        stop)
            wickServiceStop "${unparsed[@]}" "${options[@]-}" || return $?
            ;;

        *)
            wickError "Unknown service command: $action" || return $?
            wickError "Must be one of: add, add-dependency, add-dependency-if-enabled, disable, is-enabled, enable, override, reload, restart, start, stop" || return $?

            return 1
            ;;
    esac
}
