#!/bin/bash

wick-make-file() {
    local DEST DEST_FILE OWNER SET_MODE SET_OWNER SRC SRC_FILE USE_FORMULA USE_TEMPLATE

    wick-get-option USE_FORMULA formula "$@"
    wick-get-option SET_MODE mode "$@"
    wick-get-option SET_OWNER owner "$@"
    wick-get-option USE_TEMPLATE template "$@"
    wick-get-argument SRC_FILE 0 "$@"
    wick-get-argument DEST 1 "$@"
    SRC="$WICK_FORMULA_DIR"

    if [[ ! -z "$USE_FORMULA" ]]; then
        wick-find SRC "formulas/$USE_FORMULA"
    fi

    if [[ -z "$USE_TEMPLATE" ]]; then
        SRC="$SRC/files"
    else
        SRC="$SRC/templates"
    fi

    SRC="$SRC/$SRC_FILE"

    # Make sure the file exists
    if [[ ! -f "$SRC" ]]; then
        wick-error "Unable to find source file: $SRC"

        return 1
    fi

    # Write to stdout if there is no destination
    if [[ -z "$DEST" ]] || [[ "$DEST" == "-" ]]; then
        if [[ -z "$USE_TEMPLATE" ]]; then
            wick-debug "Writing file to stdout: $SRC"
            cat "$SRC"
        else
            wick-debug "Writing template to stdout: $SRC"
            formula-template "$SRC"
        fi

        return 0
    fi

    # Possible destinations, organized by how they are handled.
    # "unknown" means that there's no directory nor file with that
    # name so it is impossible to tell if the destination should be
    # a new directory or file.
    #
    # (A) /dir/that/exists/
    # (A) /dir/missing/
    # (A) /missing/dir/
    # (B) /dir/that/exists
    # (C) /dir/unknown
    # (C) /unknown/some-name
    #
    # A = Treat as a directory, append filename, treat as (C)
    # B = Add a slash then treat as (A)
    # C = Treat as a file, ensure the parent directory exists

    # First change (B) into (A)
    if [[ "${DEST: -1}" != "/" ]] && [[ -d "${DEST}" ]]; then
        DEST="${DEST}/"
    fi

    # Change (A) into (C)
    # Add the filename.
    if [[ "${DEST: -1}" == "/" ]]; then
        if [[ -z "$USE_TEMPLATE" ]]; then
            DEST="${DEST}${SRC_FILE}"
        else
            DEST="${DEST}${SRC_FILE%.*}"
        fi
    fi

    # Ensure the directory exists
    if [[ ! -d "${DEST%/*}" ]]; then
        # Preserve the owner if one was passed
        wick-make-dir "${DEST%/*}" "--owner=$SET_OWNER"
    fi

    if [[ -z "$USE_TEMPLATE" ]]; then
        # Not a template - just copy
        wick-debug "Copying $SRC to $DEST"
        cp "$SRC" "$DEST" || return 1
    else
        # Use a template
        wick-debug "Converting template $SRC into $DEST"
        formula-template "$SRC" > "$DEST" || return 1
    fi

    if [[ ! -z "$SET_OWNER" ]]; then
        wick-debug "Changing ownership: $SET_OWNER"
        chown "$SET_OWNER" "$DEST" || return 1
    fi

    if [[ ! -z "$SET_MODE" ]]; then
        wick-debug "Changing mode: $SET_MODE"
        chmod "$SET_MODE" "$DEST" || return 1
    fi
}
