#!/usr/bin/env bash
# Internal: Reloads a service.
#
# $1 - Service name to reload.
#
# Examples
#
#   wickServiceReload nginx
#
# Returns nothing.
wickServiceReload() {
    local service initType

    wickGetArgument service 0 "$@"
    wickExplorer initType wick-base init-system

    wickInfo "Reloading service: $service"

    if [[ "$initType" == systemd ]]; then
        nohup systemctl reload "$service"
    else
        nohup service "$service" reload
    fi
}
