#!/usr/bin/env bash
# Internal: Disable a service so it doesn't start on boot.
#
# $1 - Service name.
#
# Examples
#
#   wickServiceDisable consul
#
# Returns nothing.
wickServiceDisable() {
    local initType service

    wickGetArgument service 0 "$@" || return $?
    wickInfo "Disabling service: $service" || return $?

    wickExplorer initType wick-base init-system || return $?

    if [[ "$initType" == systemd ]]; then
        systemctl disable "$service" || return $?
    else
        chkconfig "$service" off || return $?
    fi
}
