#!/usr/bin/env bash
# Internal: Tell the system that an override file was updated.  This could
# shuffle the order of services in chkconfig.
#
# $1 - Service name that was updated.
#
# Examples
#
#   wickServiceMakeOverride ntp
#   sed 's/Required:/Required: myServer/' /etc/chkconfig.d/ntp
#   wickServiceOverride ntp
#
# Returns nothing.
wickServiceOverride() {
    local initType service

    wickGetArgument service 0 "$@" || return $?
    wickExplorer initType wick-base init-system || return $?
    wickInfo "Updating scripts with override for service: $service" || return $?

    if [[ "$initType" == systemd ]]; then
        # systemd will automatically pick up the override
        # file but it must be reloaded.
        systemctl daemon-reload || return $?
    else
        chkconfig --override "$service" || return $?
        chkconfig "$service" reset || return $?
    fi
}
