#!/usr/bin/env bash
# Internal: Enables a service so it starts at boot.
#
# $1 - Service name.
#
# Examples
#
#   wickServiceEnable mongod
#
# Returns nothing.
wickServiceEnable() {
    local initType service

    wickGetArgument service 0 "$@"
    wickInfo "Enabling service: $service"

    wickExplorer initType wick-base init-system

    if [[ "$initType" == systemd ]]; then
        systemctl enable "$service"
    else
        chkconfig "$service" on
    fi
}
