#!/usr/bin/env bash
# Internal: Adds the dependency to the service if that
# dependency is enabled.
#
# $1 - The service to add the dependency to
# $2 - The service name you would like to add as a dependency to $1
#
# Examples
#
#   wickServiceAddDependencyIfEnabled mysql virtual-network
#
# Returns the result of wickServiceAddDependency.
wickServiceAddDependencyIfEnabled() {
    local dependency service

    wickGetArgument service 0 "$@" || return $?
    wickGetArgument dependency 1 "$@" || return $?

    if wickServiceIsEnabled "$dependency"; then
        wickServiceAddDependency "$service" "$dependency" || return $?
    else
        wickInfo "Service $dependency does not exist.  No adding it as a dependency" || return $?
    fi
}
