#!/usr/bin/env bash
# Internal: Reloads a service.
#
# $1 - Service name to reload.
#
# Examples
#
#   wickServiceReload nginx
#
# Returns nothing.
wickServiceReload() {
    local initType service

    wickGetArgument service 0 "$@" || return $?
    wickExplorer initType wick-base init-system || return $?
    wickInfo "Reloading service: $service" || return $?

    if [[ "$initType" == systemd ]]; then
        nohup systemctl reload "$service" || return $?
    elif wickCommandExists service; then
        nohup service "$service" reload || return $?
    else
        nohup "/etc/init.d/$service reload" || return $?
    fi
}
