#!/bin/bash

wick-explorer OS wick-base os

case "$OS" in
    redhat|centos)
        wick-info "Adding Remi repository"
        ;;

    *)
        wick-info "Remi repository not needed for this OS: $OS"
        exit
esac

INSTALLED=$(rpm -qa | grep ^remi-release- || true)

if [[ ! -z "$INSTALLED" ]]; then
    wick-info "Remi package already installed: $INSTALLED"
    exit
fi

PACKAGE=$(rpm -q --whatprovides /etc/redhat-release)

wick-temp-dir TEMP

(
    cd "$TEMP"

    case "$PACKAGE" in
        *.el4.*)
            wick-get-url "http://rpms.remirepo.net/enterprise/remi-release-4.rpm" remi-release.rpm
            ;;

        *.el5.*)
            wick-get-url "http://rpms.remirepo.net/enterprise/remi-release-5.rpm" remi-release.rpm
            ;;

        *.el6.*)
            wick-get-url "http://rpms.remirepo.net/enterprise/remi-release-6.rpm" remi-release.rpm
            ;;

        *.el7.*)
            wick-get-url "http://rpms.remirepo.net/enterprise/remi-release-7.rpm" remi-release.rpm
            ;;
    esac

    if [[ -f remi-release.rpm ]]; then
        rpm -Uvh remi-release.rpm
    fi
)
