#!/usr/bin/env bash

wickExplorer OS wick-base os

case "$OS" in
    redhat|centos)
        wickInfo "Adding Remi repository"
        ;;

    *)
        wickInfo "Remi repository not needed for this OS: $OS"
        exit
esac

INSTALLED=$(rpm -qa | grep ^remi-release- || true)

if [[ ! -z "$INSTALLED" ]]; then
    wickInfo "Remi package already installed: $INSTALLED"
    exit
fi

PACKAGE=$(rpm -q --whatprovides /etc/redhat-release)

wickTempDir TEMP

(
    cd "$TEMP"

    case "$PACKAGE" in
        *.el4.*)
            wickGetUrl "http://rpms.remirepo.net/enterprise/remi-release-4.rpm" remi-release.rpm
            ;;

        *.el5.*)
            wickGetUrl "http://rpms.remirepo.net/enterprise/remi-release-5.rpm" remi-release.rpm
            ;;

        *.el6.*)
            wickGetUrl "http://rpms.remirepo.net/enterprise/remi-release-6.rpm" remi-release.rpm
            ;;

        *.el7.*)
            wickGetUrl "http://rpms.remirepo.net/enterprise/remi-release-7.rpm" remi-release.rpm
            ;;
    esac

    if [[ -f remi-release.rpm ]]; then
        rpm -Uvh remi-release.rpm
    fi
)
