#!/usr/bin/env bash
# Adds the Remi repository for yum.  Will not make it enabled by default.  Does
# nothing for other platforms that do not use yum.
#
# In order to use this properly you will need to set an extra environment
# variable with `wickPackage`.  For example, you install `redis` with this
# command.
#
# Examples
#
#   # Loading the formula.
#   wickFormula yum-remi
#
#   # Enabling the repository while installing a package.
#   YUM_ENABLE_REPO="remi" wickPackage redis
#
# Returns nothing.
declare os temp

wickExplorer os wick-base os

case "$os" in
    redhat|centos)
        wickInfo "Adding Remi repository"
        ;;

    *)
        wickInfo "Remi repository not needed for this OS: $os"
        exit
esac

installed=$(rpm -qa | grep ^remi-release- || true)

if [[ -n "$installed" ]]; then
    wickInfo "Remi package already installed: $installed"

    exit
fi

package=$(rpm -q --whatprovides /etc/redhat-release)

wickTempDir temp

(
    cd "$temp"

    case "$package" in
        *.el4.*)
            wickGetUrl "http://rpms.remirepo.net/enterprise/remi-release-4.rpm" remi-release.rpm
            ;;

        *.el5.*)
            wickGetUrl "http://rpms.remirepo.net/enterprise/remi-release-5.rpm" remi-release.rpm
            ;;

        *.el6.*)
            wickGetUrl "http://rpms.remirepo.net/enterprise/remi-release-6.rpm" remi-release.rpm
            ;;

        *.el7.*)
            wickGetUrl "http://rpms.remirepo.net/enterprise/remi-release-7.rpm" remi-release.rpm
            ;;
    esac

    if [[ -f remi-release.rpm ]]; then
        rpm -Uvh remi-release.rpm
    fi
)
